import type { Room, WallSide, EntitySnapshot } from '../types.ts';
import { GRID } from '../grid.ts';
import { syncAllPairedOpenings, isAutoGeneratedOpening } from '../adjacency.ts';
import { wallSideLength } from '../wall-object.ts';
import type { EditorContext } from './context.ts';
import { commitChange } from './project.ts';

export interface ClipboardData extends EntitySnapshot {
  originGx: number;
  originGy: number;
  bbW: number;
  bbH: number;
}

export type MirrorMode = 'none' | 'horizontal' | 'vertical';

interface BoundingBox {
  minGx: number;
  minGy: number;
  maxGx: number;
  maxGy: number;
}

function computeBoundingBox(entities: EntitySnapshot): BoundingBox {
  const { rooms, freeTexts, freeStrokes, arrows, stickyNotes } = entities;
  let minGx = Infinity;
  let minGy = Infinity;
  let maxGx = -Infinity;
  let maxGy = -Infinity;

  for (const r of rooms) {
    if (r.vertices) {
      for (const v of r.vertices) {
        minGx = Math.min(minGx, v.gx);
        minGy = Math.min(minGy, v.gy);
        maxGx = Math.max(maxGx, v.gx);
        maxGy = Math.max(maxGy, v.gy);
      }
    } else {
      minGx = Math.min(minGx, r.x);
      minGy = Math.min(minGy, r.y);
      maxGx = Math.max(maxGx, r.x + r.w);
      maxGy = Math.max(maxGy, r.y + r.h);
    }
  }

  for (const ft of freeTexts) {
    minGx = Math.min(minGx, ft.gx);
    minGy = Math.min(minGy, ft.gy);
    maxGx = Math.max(maxGx, ft.gx + ft.w);
    maxGy = Math.max(maxGy, ft.gy + ft.h);
  }

  for (const fs of freeStrokes) {
    for (const p of fs.points) {
      const gx = p.px / GRID;
      const gy = p.py / GRID;
      minGx = Math.min(minGx, gx);
      minGy = Math.min(minGy, gy);
      maxGx = Math.max(maxGx, gx);
      maxGy = Math.max(maxGy, gy);
    }
  }

  for (const a of arrows) {
    for (const p of a.points) {
      minGx = Math.min(minGx, p.gx);
      minGy = Math.min(minGy, p.gy);
      maxGx = Math.max(maxGx, p.gx);
      maxGy = Math.max(maxGy, p.gy);
    }
  }

  for (const n of stickyNotes) {
    minGx = Math.min(minGx, n.gx);
    minGy = Math.min(minGy, n.gy);
    maxGx = Math.max(maxGx, n.gx + n.w);
    maxGy = Math.max(maxGy, n.gy + n.h);
  }

  return { minGx, minGy, maxGx, maxGy };
}

function cleanRoomForClipboard(room: Room): void {
  // Remove pairedWith from all WallObjects
  if (room.wallObjects) {
    room.wallObjects = room.wallObjects.filter((o) => !isAutoGeneratedOpening(o));
    for (const obj of room.wallObjects) {
      delete obj.pairedWith;
    }
    if (room.wallObjects.length === 0) room.wallObjects = undefined;
  }
  // Remove linkGroup
  delete room.linkGroup;
}

export function copySelection(ec: EditorContext): void {
  const { state, flags } = ec;
  if (state.selection.size === 0) return;

  const rooms = state.rooms.filter((r) => state.selection.has(r.id));
  const freeTexts = state.freeTexts.filter((ft) => state.selection.has(ft.id));
  const freeStrokes = state.freeStrokes.filter((fs) => state.selection.has(fs.id));
  const arrows = state.arrows.filter((a) => state.selection.has(a.id));
  const stickyNotes = state.stickyNotes.filter((n) => state.selection.has(n.id));

  if (
    rooms.length === 0 &&
    freeTexts.length === 0 &&
    freeStrokes.length === 0 &&
    arrows.length === 0 &&
    stickyNotes.length === 0
  )
    return;

  const cloned: EntitySnapshot = structuredClone({
    rooms,
    freeTexts,
    freeStrokes,
    arrows,
    stickyNotes,
  });

  for (const r of cloned.rooms) {
    cleanRoomForClipboard(r);
  }

  const bb = computeBoundingBox(cloned);

  flags.clipboard = {
    ...cloned,
    originGx: bb.minGx,
    originGy: bb.minGy,
    bbW: bb.maxGx - bb.minGx,
    bbH: bb.maxGy - bb.minGy,
  };
}

function regenerateIds(entities: EntitySnapshot): void {
  const { rooms, freeTexts, freeStrokes, arrows, stickyNotes } = entities;
  for (const r of rooms) {
    r.id = crypto.randomUUID();
    if (r.wallObjects) {
      for (const obj of r.wallObjects) {
        obj.id = crypto.randomUUID();
      }
    }
    if (r.interiorObjects) {
      for (const obj of r.interiorObjects) {
        obj.id = crypto.randomUUID();
      }
    }
  }
  for (const ft of freeTexts) {
    ft.id = crypto.randomUUID();
  }
  for (const fs of freeStrokes) {
    fs.id = crypto.randomUUID();
  }
  for (const a of arrows) {
    a.id = crypto.randomUUID();
  }
  for (const n of stickyNotes) {
    n.id = crypto.randomUUID();
  }
}

function flipSideHorizontal(side: WallSide): WallSide {
  if (side === 'e') return 'w';
  if (side === 'w') return 'e';
  return side;
}

function flipSideVertical(side: WallSide): WallSide {
  if (side === 'n') return 's';
  if (side === 's') return 'n';
  return side;
}

function normalizeAngle(a: number): number {
  const TWO_PI = Math.PI * 2;
  return ((a % TWO_PI) + TWO_PI) % TWO_PI;
}

function applyMirrorHorizontal(entities: EntitySnapshot, centerGx: number): void {
  const { rooms, freeTexts, freeStrokes, arrows, stickyNotes } = entities;
  const centerPx = centerGx * GRID;

  for (const room of rooms) {
    // Pre-compute wall side lengths and room dimensions BEFORE vertex mirroring,
    // so WallObject offset and InteriorObject position calculations use original values.
    // For polygon rooms, vertex reordering changes edge-side mapping, which would
    // cause wallSideLength/room.w to return values for the wrong side after update.
    const preW = room.w;
    const preSideLengths = new Map<WallSide, number>();
    if (room.wallObjects) {
      for (const obj of room.wallObjects) {
        if (!preSideLengths.has(obj.side)) {
          preSideLengths.set(obj.side, wallSideLength(room, obj.side));
        }
      }
    }

    if (room.vertices) {
      // Mirror vertices and reorder to maintain edge-side correspondence:
      // edges 0->1, 1->2, 2->3, 3->0 map to n, e, s, w sides.
      // Horizontal flip swaps left/right, so reorder [v1,v0,v3,v2] preserves winding.
      for (const v of room.vertices) {
        v.gx = 2 * centerGx - v.gx;
      }
      const [v0, v1, v2, v3] = room.vertices;
      room.vertices = [v1, v0, v3, v2];
      // Update bounding box from vertices
      const gxs = room.vertices.map((v) => v.gx);
      const gys = room.vertices.map((v) => v.gy);
      room.x = Math.min(...gxs);
      room.y = Math.min(...gys);
      room.w = Math.max(...gxs) - room.x;
      room.h = Math.max(...gys) - room.y;
    } else {
      room.x = 2 * centerGx - room.x - room.w;
    }

    if (room.wallObjects) {
      for (const obj of room.wallObjects) {
        const origSide = obj.side;
        obj.side = flipSideHorizontal(origSide);
        // For n/s walls, offset needs flipping
        if (origSide === 'n' || origSide === 's') {
          const sideLen = preSideLengths.get(origSide)!;
          obj.offset = sideLen - obj.offset - obj.width;
        }
        // Door hinge flip for n/s walls
        if (obj.type === 'door' && (origSide === 'n' || origSide === 's')) {
          obj.hinge = obj.hinge === 'start' ? 'end' : 'start';
        }
      }
    }

    if (room.interiorObjects) {
      for (const obj of room.interiorObjects) {
        obj.x = preW - obj.x - obj.w;
        if (obj.type === 'stairs' || obj.type === 'marker') {
          if (obj.direction === 'e') obj.direction = 'w';
          else if (obj.direction === 'w') obj.direction = 'e';
        }
        if (obj.type === 'camera') {
          obj.angle = normalizeAngle(Math.PI - obj.angle);
        }
      }
    }
  }

  for (const ft of freeTexts) {
    ft.gx = 2 * centerGx - ft.gx - ft.w;
  }

  for (const fs of freeStrokes) {
    for (const p of fs.points) {
      p.px = 2 * centerPx - p.px;
    }
  }

  for (const a of arrows) {
    for (const p of a.points) {
      p.gx = 2 * centerGx - p.gx;
    }
  }

  for (const n of stickyNotes) {
    n.gx = 2 * centerGx - n.gx - n.w;
  }
}

function applyMirrorVertical(entities: EntitySnapshot, centerGy: number): void {
  const { rooms, freeTexts, freeStrokes, arrows, stickyNotes } = entities;
  const centerPy = centerGy * GRID;

  for (const room of rooms) {
    // Pre-compute wall side lengths and room dimensions BEFORE vertex mirroring
    const preH = room.h;
    const preSideLengths = new Map<WallSide, number>();
    if (room.wallObjects) {
      for (const obj of room.wallObjects) {
        if (!preSideLengths.has(obj.side)) {
          preSideLengths.set(obj.side, wallSideLength(room, obj.side));
        }
      }
    }

    if (room.vertices) {
      // Vertical flip swaps top/bottom, reorder [v3,v2,v1,v0] preserves winding.
      for (const v of room.vertices) {
        v.gy = 2 * centerGy - v.gy;
      }
      const [v0, v1, v2, v3] = room.vertices;
      room.vertices = [v3, v2, v1, v0];
      const gxs = room.vertices.map((v) => v.gx);
      const gys = room.vertices.map((v) => v.gy);
      room.x = Math.min(...gxs);
      room.y = Math.min(...gys);
      room.w = Math.max(...gxs) - room.x;
      room.h = Math.max(...gys) - room.y;
    } else {
      room.y = 2 * centerGy - room.y - room.h;
    }

    if (room.wallObjects) {
      for (const obj of room.wallObjects) {
        const origSide = obj.side;
        obj.side = flipSideVertical(origSide);
        // For e/w walls, offset needs flipping
        if (origSide === 'e' || origSide === 'w') {
          const sideLen = preSideLengths.get(origSide)!;
          obj.offset = sideLen - obj.offset - obj.width;
        }
        // Door hinge flip for e/w walls
        if (obj.type === 'door' && (origSide === 'e' || origSide === 'w')) {
          obj.hinge = obj.hinge === 'start' ? 'end' : 'start';
        }
      }
    }

    if (room.interiorObjects) {
      for (const obj of room.interiorObjects) {
        obj.y = preH - obj.y - obj.h;
        if (obj.type === 'stairs' || obj.type === 'marker') {
          if (obj.direction === 'n') obj.direction = 's';
          else if (obj.direction === 's') obj.direction = 'n';
        }
        if (obj.type === 'camera') {
          obj.angle = normalizeAngle(-obj.angle);
        }
      }
    }
  }

  for (const ft of freeTexts) {
    ft.gy = 2 * centerGy - ft.gy - ft.h;
  }

  for (const fs of freeStrokes) {
    for (const p of fs.points) {
      p.py = 2 * centerPy - p.py;
    }
  }

  for (const a of arrows) {
    for (const p of a.points) {
      p.gy = 2 * centerGy - p.gy;
    }
  }

  for (const n of stickyNotes) {
    n.gy = 2 * centerGy - n.gy - n.h;
  }
}

function applyOffset(entities: EntitySnapshot, dx: number, dy: number): void {
  const { rooms, freeTexts, freeStrokes, arrows, stickyNotes } = entities;
  for (const room of rooms) {
    room.x += dx;
    room.y += dy;
    if (room.vertices) {
      for (const v of room.vertices) {
        v.gx += dx;
        v.gy += dy;
      }
    }
  }
  for (const ft of freeTexts) {
    ft.gx += dx;
    ft.gy += dy;
  }
  for (const fs of freeStrokes) {
    for (const p of fs.points) {
      p.px += dx * GRID;
      p.py += dy * GRID;
    }
  }
  for (const a of arrows) {
    for (const p of a.points) {
      p.gx += dx;
      p.gy += dy;
    }
  }
  for (const n of stickyNotes) {
    n.gx += dx;
    n.gy += dy;
  }
}

export function pasteClipboard(
  ec: EditorContext,
  mirror: MirrorMode,
  targetPos?: { gx: number; gy: number },
): void {
  const { state, flags } = ec;
  const clipboard = flags.clipboard;
  if (!clipboard) return;

  const { rooms, freeTexts, freeStrokes, arrows, stickyNotes } = clipboard;
  const cloned: EntitySnapshot = structuredClone({
    rooms,
    freeTexts,
    freeStrokes,
    arrows,
    stickyNotes,
  });

  // Apply mirror before offset (mirror around clipboard center)
  if (mirror === 'horizontal') {
    const centerGx = clipboard.originGx + clipboard.bbW / 2;
    applyMirrorHorizontal(cloned, centerGx);
  } else if (mirror === 'vertical') {
    const centerGy = clipboard.originGy + clipboard.bbH / 2;
    applyMirrorVertical(cloned, centerGy);
  }

  regenerateIds(cloned);

  // Offset to target position (defaults to current mouse position).
  // Intentionally round to integer grid — paste always snaps to full grid units
  // even when Shift sub-grid mode provides fractional coordinates.
  const pos = targetPos ?? state.mouse;
  const dx = Math.round(pos.gx - clipboard.originGx);
  const dy = Math.round(pos.gy - clipboard.originGy);
  applyOffset(cloned, dx, dy);

  // Update selection inside commitChange so a single render() covers both data and selection
  commitChange(ec, () => {
    state.rooms.push(...cloned.rooms);
    state.freeTexts.push(...cloned.freeTexts);
    state.freeStrokes.push(...cloned.freeStrokes);
    state.arrows.push(...cloned.arrows);
    state.stickyNotes.push(...cloned.stickyNotes);
    syncAllPairedOpenings(state.rooms);

    state.selection.clear();
    for (const r of cloned.rooms) state.selection.add(r.id);
    for (const ft of cloned.freeTexts) state.selection.add(ft.id);
    for (const fs of cloned.freeStrokes) state.selection.add(fs.id);
    for (const a of cloned.arrows) state.selection.add(a.id);
    for (const n of cloned.stickyNotes) state.selection.add(n.id);
  });
}

export function duplicateSelection(ec: EditorContext): void {
  const savedClipboard = ec.flags.clipboard;
  copySelection(ec);
  const clipboard = ec.flags.clipboard;
  if (!clipboard) {
    ec.flags.clipboard = savedClipboard;
    return;
  }

  // Paste at 1 grid offset right-down from origin
  pasteClipboard(ec, 'none', {
    gx: clipboard.originGx + 1,
    gy: clipboard.originGy + 1,
  });

  // Restore original clipboard so ⌘D doesn't destroy ⌘C content
  ec.flags.clipboard = savedClipboard;
}

// Exported for testing
export {
  computeBoundingBox as _computeBoundingBox,
  applyMirrorHorizontal as _applyMirrorHorizontal,
  applyMirrorVertical as _applyMirrorVertical,
  cleanRoomForClipboard as _cleanRoomForClipboard,
  regenerateIds as _regenerateIds,
  applyOffset as _applyOffset,
};
