import { describe, it, expect, vi } from 'vitest';
import type { Room, FreeText, FreeStroke, EntitySnapshot, GridPoint } from '../types.ts';
import type { EditorContext } from './context.ts';
import {
  copySelection,
  pasteClipboard,
  duplicateSelection,
  _computeBoundingBox,
  _applyMirrorHorizontal,
  _applyMirrorVertical,
  _cleanRoomForClipboard,
} from './clipboard.ts';

function ents(
  rooms: Room[] = [],
  freeTexts: FreeText[] = [],
  freeStrokes: FreeStroke[] = [],
): EntitySnapshot {
  return { rooms, freeTexts, freeStrokes, arrows: [] };
}

function makeRoom(overrides: Partial<Room> = {}): Room {
  return {
    id: crypto.randomUUID(),
    x: 0,
    y: 0,
    w: 4,
    h: 3,
    label: 'Room',
    ...overrides,
  };
}

function makeFreeText(overrides: Partial<FreeText> = {}): FreeText {
  return {
    id: crypto.randomUUID(),
    gx: 0,
    gy: 0,
    w: 2,
    h: 1,
    label: 'Text',
    fontSize: 14,
    zLayer: 'front',
    ...overrides,
  };
}

function makeFreeStroke(overrides: Partial<FreeStroke> = {}): FreeStroke {
  return {
    id: crypto.randomUUID(),
    points: [
      { px: 0, py: 0 },
      { px: 40, py: 60 },
    ],
    color: '#ff0000',
    lineWidth: 3,
    opacity: 1,
    ...overrides,
  };
}

function makeEc(
  rooms: Room[] = [],
  freeTexts: FreeText[] = [],
  freeStrokes: FreeStroke[] = [],
  selection: Set<string> = new Set(),
): EditorContext {
  return {
    canvas: {} as HTMLCanvasElement,
    ctx: {} as CanvasRenderingContext2D,
    container: {} as HTMLElement,
    state: {
      rooms,
      freeTexts,
      freeStrokes,
      arrows: [],
      selection,
      history: [],
      redoHistory: [],
      drag: null,
      mouse: { px: 0, py: 0, gx: 0, gy: 0 },
      paintMode: false,
      paintColor: '#ff0000',
      paintLineWidth: 3,
      paintOpacity: 1.0,
      arrowMode: false,
      arrowColor: '#cc0000',
      arrowLineWidth: 2,
    },
    viewport: { zoom: 1, panX: 0, panY: 0 },
    callbacks: {
      onStatusChange: vi.fn(),
      onRoomEdit: vi.fn(),
      onMarkerEdit: vi.fn(),
      onFreeTextEdit: vi.fn(),
      onContextMenu: vi.fn(),
      onAutoSave: vi.fn(),
      onViewportChange: vi.fn(),
    },
    flags: {
      isPanning: false,
      activeInteriorObjectId: undefined,
      activeFreeTextId: undefined,
      snapIndicator: null,
      clipboard: null,
      savedRedo: null,
      pendingArrow: null,
    },
    render: vi.fn(),
    commitChange: vi.fn((fn: () => void) => fn()),
    mousePos: vi.fn(),
  } as unknown as EditorContext;
}

describe('copySelection', () => {
  it('copies a single room with WallObjects and InteriorObjects', () => {
    const room = makeRoom({
      wallObjects: [
        { id: 'w1', type: 'window', side: 'n', offset: 1, width: 1 },
        {
          id: 'w2',
          type: 'opening',
          side: 'e',
          offset: 0,
          width: 1,
          autoGenerated: true,
          pairedWith: [{ roomId: 'other', objectId: 'o1' }],
        },
      ],
      interiorObjects: [
        {
          id: 'i1',
          type: 'stairs',
          stairsType: 'straight',
          x: 0,
          y: 0,
          w: 2,
          h: 3,
          direction: 'n',
        },
      ],
      linkGroup: 'group1',
    });
    const ec = makeEc([room], [], [], new Set([room.id]));
    copySelection(ec);

    const cb = ec.flags.clipboard!;
    expect(cb).not.toBeNull();
    expect(cb.rooms).toHaveLength(1);
    // autoGenerated opening should be removed
    expect(cb.rooms[0].wallObjects).toHaveLength(1);
    expect(cb.rooms[0].wallObjects![0].type).toBe('window');
    // pairedWith should be deleted
    expect(cb.rooms[0].wallObjects![0].pairedWith).toBeUndefined();
    // linkGroup should be deleted
    expect(cb.rooms[0].linkGroup).toBeUndefined();
    // InteriorObjects preserved
    expect(cb.rooms[0].interiorObjects).toHaveLength(1);
  });

  it('copies multiple rooms preserving relative positions', () => {
    const r1 = makeRoom({ x: 2, y: 3, w: 4, h: 3 });
    const r2 = makeRoom({ x: 8, y: 5, w: 3, h: 2 });
    const ec = makeEc([r1, r2], [], [], new Set([r1.id, r2.id]));
    copySelection(ec);

    const cb = ec.flags.clipboard!;
    expect(cb.rooms).toHaveLength(2);
    expect(cb.originGx).toBe(2);
    expect(cb.originGy).toBe(3);
    expect(cb.bbW).toBe(9); // 8+3-2=9
    expect(cb.bbH).toBe(4); // 5+2-3=4
  });

  it('copies FreeText and FreeStroke', () => {
    const ft = makeFreeText({ gx: 5, gy: 6, w: 2, h: 1 });
    const fs = makeFreeStroke({
      points: [
        { px: 100, py: 200 },
        { px: 140, py: 260 },
      ],
    });
    const ec = makeEc([], [ft], [fs], new Set([ft.id, fs.id]));
    copySelection(ec);

    const cb = ec.flags.clipboard!;
    expect(cb.freeTexts).toHaveLength(1);
    expect(cb.freeStrokes).toHaveLength(1);
  });

  it('does nothing when selection is empty', () => {
    const ec = makeEc([makeRoom()], [], [], new Set());
    copySelection(ec);
    expect(ec.flags.clipboard).toBeNull();
  });
});

describe('pasteClipboard', () => {
  it('pastes at cursor position with offset', () => {
    const room = makeRoom({ x: 2, y: 3, w: 4, h: 3 });
    const ec = makeEc([room], [], [], new Set([room.id]));
    copySelection(ec);

    // Move mouse to (10, 10)
    ec.state.mouse = { px: 200, py: 200, gx: 10, gy: 10 };
    pasteClipboard(ec, 'none');

    // Should have 2 rooms now
    expect(ec.state.rooms).toHaveLength(2);
    const pasted = ec.state.rooms[1];
    // dx = 10-2 = 8, dy = 10-3 = 7
    expect(pasted.x).toBe(10);
    expect(pasted.y).toBe(10);
    expect(pasted.w).toBe(4);
    expect(pasted.h).toBe(3);
  });

  it('regenerates UUIDs for all objects', () => {
    const room = makeRoom({
      wallObjects: [{ id: 'w1', type: 'window', side: 'n', offset: 1, width: 1 }],
      interiorObjects: [
        {
          id: 'i1',
          type: 'stairs',
          stairsType: 'straight',
          x: 0,
          y: 0,
          w: 2,
          h: 3,
          direction: 'n',
        },
      ],
    });
    const ec = makeEc([room], [], [], new Set([room.id]));
    copySelection(ec);

    ec.state.mouse = { px: 0, py: 0, gx: 0, gy: 0 };
    pasteClipboard(ec, 'none');

    const pasted = ec.state.rooms[1];
    expect(pasted.id).not.toBe(room.id);
    expect(pasted.wallObjects![0].id).not.toBe('w1');
    expect(pasted.interiorObjects![0].id).not.toBe('i1');
  });

  it('generates different IDs on each paste', () => {
    const room = makeRoom();
    const ec = makeEc([room], [], [], new Set([room.id]));
    copySelection(ec);

    ec.state.mouse = { px: 0, py: 0, gx: 0, gy: 0 };
    pasteClipboard(ec, 'none');
    const id1 = ec.state.rooms[1].id;

    pasteClipboard(ec, 'none');
    const id2 = ec.state.rooms[2].id;

    expect(id1).not.toBe(id2);
  });

  it('does nothing when clipboard is null', () => {
    const ec = makeEc([], [], [], new Set());
    pasteClipboard(ec, 'none');
    expect(ec.state.rooms).toHaveLength(0);
  });

  it('updates selection to pasted elements', () => {
    const room = makeRoom();
    const ec = makeEc([room], [], [], new Set([room.id]));
    copySelection(ec);

    ec.state.mouse = { px: 0, py: 0, gx: 5, gy: 5 };
    pasteClipboard(ec, 'none');

    expect(ec.state.selection.size).toBe(1);
    expect(ec.state.selection.has(room.id)).toBe(false);
    expect(ec.state.selection.has(ec.state.rooms[1].id)).toBe(true);
  });
});

describe('mirror horizontal', () => {
  it('mirrors room position', () => {
    const rooms: Room[] = [makeRoom({ x: 2, y: 3, w: 4, h: 3 })];
    // BB center: 2 + 4/2 = 4
    _applyMirrorHorizontal(ents(rooms),4);
    // x = 2*4 - 2 - 4 = 2 (symmetric around center)
    expect(rooms[0].x).toBe(2);
  });

  it('mirrors room off-center', () => {
    const rooms: Room[] = [makeRoom({ x: 1, y: 0, w: 2, h: 2 })];
    // centerGx = 3 (e.g. bb from 1 to 5)
    _applyMirrorHorizontal(ents(rooms),3);
    // x = 2*3 - 1 - 2 = 3
    expect(rooms[0].x).toBe(3);
  });

  it('flips WallObject side e↔w', () => {
    const rooms: Room[] = [
      makeRoom({
        x: 0,
        y: 0,
        w: 4,
        h: 3,
        wallObjects: [
          { id: 'w1', type: 'window', side: 'e', offset: 1, width: 1 },
          { id: 'w2', type: 'window', side: 'n', offset: 1, width: 1 },
        ],
      }),
    ];
    _applyMirrorHorizontal(ents(rooms),2);
    expect(rooms[0].wallObjects![0].side).toBe('w');
    expect(rooms[0].wallObjects![1].side).toBe('n');
  });

  it('flips WallObject offset on n/s walls', () => {
    const rooms: Room[] = [
      makeRoom({
        x: 0,
        y: 0,
        w: 6,
        h: 3,
        wallObjects: [{ id: 'w1', type: 'window', side: 'n', offset: 1, width: 2 }],
      }),
    ];
    _applyMirrorHorizontal(ents(rooms),3);
    // offset = 6 - 1 - 2 = 3
    expect(rooms[0].wallObjects![0].offset).toBe(3);
  });

  it('flips door hinge on n/s walls', () => {
    const rooms: Room[] = [
      makeRoom({
        x: 0,
        y: 0,
        w: 4,
        h: 3,
        wallObjects: [
          {
            id: 'd1',
            type: 'door',
            side: 'n',
            offset: 1,
            width: 1,
            swing: 'inward',
            hinge: 'start',
          },
        ],
      }),
    ];
    _applyMirrorHorizontal(ents(rooms),2);
    expect(rooms[0].wallObjects![0].type).toBe('door');
    if (rooms[0].wallObjects![0].type === 'door') {
      expect(rooms[0].wallObjects![0].hinge).toBe('end');
    }
  });

  it('flips InteriorObject direction e↔w', () => {
    const rooms: Room[] = [
      makeRoom({
        x: 0,
        y: 0,
        w: 4,
        h: 3,
        interiorObjects: [
          {
            id: 'i1',
            type: 'stairs',
            stairsType: 'straight',
            x: 1,
            y: 0,
            w: 2,
            h: 3,
            direction: 'e',
          },
        ],
      }),
    ];
    _applyMirrorHorizontal(ents(rooms),2);
    expect(rooms[0].interiorObjects![0]).toHaveProperty('direction', 'w');
    // x = 4 - 1 - 2 = 1
    expect(rooms[0].interiorObjects![0].x).toBe(1);
  });

  it('flips camera angle', () => {
    const rooms: Room[] = [
      makeRoom({
        x: 0,
        y: 0,
        w: 4,
        h: 3,
        interiorObjects: [
          {
            id: 'c1',
            type: 'camera',
            x: 0,
            y: 0,
            w: 1,
            h: 1,
            angle: Math.PI / 4,
            fovAngle: Math.PI / 6,
            fovRange: 5,
            fovColor: 'rgba(0,150,255,0.15)',
            fovStrokeColor: 'rgba(0,150,255,0.4)',
          },
        ],
      }),
    ];
    _applyMirrorHorizontal(ents(rooms),2);
    const cam = rooms[0].interiorObjects![0];
    if (cam.type === 'camera') {
      // PI - PI/4 = 3*PI/4
      expect(cam.angle).toBeCloseTo((3 * Math.PI) / 4);
    }
  });

  it('mirrors polygon vertices and reorders [v1,v0,v3,v2]', () => {
    const v: [GridPoint, GridPoint, GridPoint, GridPoint] = [
      { gx: 0, gy: 0 },
      { gx: 4, gy: 0 },
      { gx: 4, gy: 3 },
      { gx: 0, gy: 3 },
    ];
    const rooms: Room[] = [makeRoom({ x: 0, y: 0, w: 4, h: 3, vertices: v })];
    _applyMirrorHorizontal(ents(rooms),2);
    // After mirror: gx = 2*2 - gx for each
    // Original v0(0)->4, v1(4)->0, v2(4)->0, v3(0)->4
    // Reorder [v1,v0,v3,v2] => [{gx:0},{gx:4},{gx:4},{gx:0}]
    expect(rooms[0].vertices![0].gx).toBe(0);
    expect(rooms[0].vertices![1].gx).toBe(4);
    expect(rooms[0].vertices![2].gx).toBe(4);
    expect(rooms[0].vertices![3].gx).toBe(0);
  });

  it('mirrors polygon room with WallObject using pre-computed side length', () => {
    // Trapezoid: top edge (n) is shorter than bottom edge (s)
    // n edge: (1,0)->(3,0) = length 2
    // s edge: (0,3)->(4,3) = length 4
    const v: [GridPoint, GridPoint, GridPoint, GridPoint] = [
      { gx: 1, gy: 0 },
      { gx: 3, gy: 0 },
      { gx: 4, gy: 3 },
      { gx: 0, gy: 3 },
    ];
    const rooms: Room[] = [
      makeRoom({
        x: 0,
        y: 0,
        w: 4,
        h: 3,
        vertices: v,
        wallObjects: [{ id: 'w1', type: 'window', side: 'n', offset: 0.5, width: 1 }],
      }),
    ];
    _applyMirrorHorizontal(ents(rooms),2);
    // n edge length was 2 (pre-computed), so offset = 2 - 0.5 - 1 = 0.5
    expect(rooms[0].wallObjects![0].offset).toBe(0.5);
  });

  it('mirrors polygon room InteriorObject using pre-computed room width', () => {
    const v: [GridPoint, GridPoint, GridPoint, GridPoint] = [
      { gx: 1, gy: 0 },
      { gx: 3, gy: 0 },
      { gx: 4, gy: 3 },
      { gx: 0, gy: 3 },
    ];
    const rooms: Room[] = [
      makeRoom({
        x: 0,
        y: 0,
        w: 4,
        h: 3,
        vertices: v,
        interiorObjects: [
          {
            id: 'i1',
            type: 'stairs',
            stairsType: 'straight',
            x: 0,
            y: 0,
            w: 2,
            h: 3,
            direction: 'e',
          },
        ],
      }),
    ];
    _applyMirrorHorizontal(ents(rooms),2);
    // preW = 4, so x = 4 - 0 - 2 = 2
    expect(rooms[0].interiorObjects![0].x).toBe(2);
    expect(rooms[0].interiorObjects![0]).toHaveProperty('direction', 'w');
  });

  it('mirrors FreeText position', () => {
    const freeTexts: FreeText[] = [makeFreeText({ gx: 1, gy: 2, w: 3, h: 1 })];
    _applyMirrorHorizontal(ents([], freeTexts),4);
    // gx = 2*4 - 1 - 3 = 4
    expect(freeTexts[0].gx).toBe(4);
  });

  it('mirrors FreeStroke points', () => {
    const freeStrokes: FreeStroke[] = [
      makeFreeStroke({
        points: [
          { px: 20, py: 40 },
          { px: 60, py: 80 },
        ],
      }),
    ];
    // centerGx=2, centerPx=2*20=40
    _applyMirrorHorizontal(ents([], [], freeStrokes),2);
    // px[0] = 2*40 - 20 = 60
    expect(freeStrokes[0].points[0].px).toBe(60);
    // px[1] = 2*40 - 60 = 20
    expect(freeStrokes[0].points[1].px).toBe(20);
  });
});

describe('mirror vertical', () => {
  it('mirrors room position', () => {
    const rooms: Room[] = [makeRoom({ x: 0, y: 1, w: 4, h: 2 })];
    _applyMirrorVertical(ents(rooms),3);
    // y = 2*3 - 1 - 2 = 3
    expect(rooms[0].y).toBe(3);
  });

  it('flips WallObject side n↔s', () => {
    const rooms: Room[] = [
      makeRoom({
        wallObjects: [
          { id: 'w1', type: 'window', side: 'n', offset: 1, width: 1 },
          { id: 'w2', type: 'window', side: 'e', offset: 1, width: 1 },
        ],
      }),
    ];
    _applyMirrorVertical(ents(rooms),1.5);
    expect(rooms[0].wallObjects![0].side).toBe('s');
    expect(rooms[0].wallObjects![1].side).toBe('e');
  });

  it('flips WallObject offset on e/w walls', () => {
    const rooms: Room[] = [
      makeRoom({
        x: 0,
        y: 0,
        w: 4,
        h: 6,
        wallObjects: [{ id: 'w1', type: 'window', side: 'e', offset: 1, width: 2 }],
      }),
    ];
    _applyMirrorVertical(ents(rooms),3);
    // offset = 6 - 1 - 2 = 3
    expect(rooms[0].wallObjects![0].offset).toBe(3);
  });

  it('flips door hinge on e/w walls', () => {
    const rooms: Room[] = [
      makeRoom({
        wallObjects: [
          {
            id: 'd1',
            type: 'door',
            side: 'w',
            offset: 1,
            width: 1,
            swing: 'inward',
            hinge: 'start',
          },
        ],
      }),
    ];
    _applyMirrorVertical(ents(rooms),1.5);
    if (rooms[0].wallObjects![0].type === 'door') {
      expect(rooms[0].wallObjects![0].hinge).toBe('end');
    }
  });

  it('flips InteriorObject direction n↔s', () => {
    const rooms: Room[] = [
      makeRoom({
        interiorObjects: [
          {
            id: 'i1',
            type: 'stairs',
            stairsType: 'straight',
            x: 0,
            y: 0,
            w: 2,
            h: 3,
            direction: 'n',
          },
        ],
      }),
    ];
    _applyMirrorVertical(ents(rooms),1.5);
    expect(rooms[0].interiorObjects![0]).toHaveProperty('direction', 's');
  });

  it('flips camera angle vertically', () => {
    const rooms: Room[] = [
      makeRoom({
        interiorObjects: [
          {
            id: 'c1',
            type: 'camera',
            x: 0,
            y: 0,
            w: 1,
            h: 1,
            angle: Math.PI / 4,
            fovAngle: Math.PI / 6,
            fovRange: 5,
            fovColor: 'rgba(0,150,255,0.15)',
            fovStrokeColor: 'rgba(0,150,255,0.4)',
          },
        ],
      }),
    ];
    _applyMirrorVertical(ents(rooms),1.5);
    const cam = rooms[0].interiorObjects![0];
    if (cam.type === 'camera') {
      // -PI/4 normalized = 7*PI/4
      expect(cam.angle).toBeCloseTo((7 * Math.PI) / 4);
    }
  });

  it('mirrors polygon vertices and reorders [v3,v2,v1,v0]', () => {
    const v: [GridPoint, GridPoint, GridPoint, GridPoint] = [
      { gx: 0, gy: 0 },
      { gx: 4, gy: 0 },
      { gx: 4, gy: 3 },
      { gx: 0, gy: 3 },
    ];
    const rooms: Room[] = [makeRoom({ vertices: v })];
    _applyMirrorVertical(ents(rooms),1.5);
    // After mirror: gy = 2*1.5 - gy
    // v0(0)->3, v1(0)->3, v2(3)->0, v3(3)->0
    // Reorder [v3,v2,v1,v0] => [{gy:0},{gy:0},{gy:3},{gy:3}]
    expect(rooms[0].vertices![0].gy).toBe(0);
    expect(rooms[0].vertices![1].gy).toBe(0);
    expect(rooms[0].vertices![2].gy).toBe(3);
    expect(rooms[0].vertices![3].gy).toBe(3);
  });

  it('mirrors FreeText position', () => {
    const freeTexts: FreeText[] = [makeFreeText({ gx: 1, gy: 2, w: 3, h: 1 })];
    _applyMirrorVertical(ents([], freeTexts),4);
    // gy = 2*4 - 2 - 1 = 5
    expect(freeTexts[0].gy).toBe(5);
  });

  it('mirrors FreeStroke points', () => {
    const freeStrokes: FreeStroke[] = [
      makeFreeStroke({
        points: [
          { px: 20, py: 40 },
          { px: 60, py: 80 },
        ],
      }),
    ];
    _applyMirrorVertical(ents([], [], freeStrokes),3);
    // centerPy = 3*20 = 60
    // py[0] = 2*60 - 40 = 80
    // py[1] = 2*60 - 80 = 40
    expect(freeStrokes[0].points[0].py).toBe(80);
    expect(freeStrokes[0].points[1].py).toBe(40);
  });
});

describe('duplicateSelection', () => {
  it('creates a copy offset by 1 grid', () => {
    const room = makeRoom({ x: 5, y: 5, w: 4, h: 3 });
    const ec = makeEc([room], [], [], new Set([room.id]));
    duplicateSelection(ec);

    expect(ec.state.rooms).toHaveLength(2);
    const dup = ec.state.rooms[1];
    expect(dup.x).toBe(6);
    expect(dup.y).toBe(6);
    expect(dup.id).not.toBe(room.id);
  });

  it('duplicates FreeText offset by 1 grid', () => {
    const ft = makeFreeText({ gx: 3, gy: 4, w: 2, h: 1 });
    const ec = makeEc([], [ft], [], new Set([ft.id]));
    duplicateSelection(ec);

    expect(ec.state.freeTexts).toHaveLength(2);
    const dup = ec.state.freeTexts[1];
    expect(dup.gx).toBe(4);
    expect(dup.gy).toBe(5);
    expect(dup.id).not.toBe(ft.id);
  });

  it('duplicates FreeStroke offset by 1 grid', () => {
    const fs = makeFreeStroke({
      points: [
        { px: 60, py: 80 },
        { px: 100, py: 120 },
      ],
    });
    const ec = makeEc([], [], [fs], new Set([fs.id]));
    duplicateSelection(ec);

    expect(ec.state.freeStrokes).toHaveLength(2);
    const dup = ec.state.freeStrokes[1];
    // dx=1, dy=1 → px += 20, py += 20
    expect(dup.points[0].px).toBe(80);
    expect(dup.points[0].py).toBe(100);
    expect(dup.points[1].px).toBe(120);
    expect(dup.points[1].py).toBe(140);
    expect(dup.id).not.toBe(fs.id);
  });

  it('preserves original clipboard after duplicate', () => {
    const room = makeRoom({ x: 0, y: 0, w: 4, h: 3 });
    const ec = makeEc([room], [], [], new Set([room.id]));
    // First copy something
    copySelection(ec);
    const originalClipboard = ec.flags.clipboard;

    // Then duplicate (should not destroy clipboard)
    duplicateSelection(ec);

    expect(ec.flags.clipboard).toBe(originalClipboard);
  });
});

describe('cleanRoomForClipboard', () => {
  it('removes autoGenerated openings and pairedWith', () => {
    const room = makeRoom({
      wallObjects: [
        {
          id: 'w1',
          type: 'window',
          side: 'n',
          offset: 1,
          width: 1,
          pairedWith: [{ roomId: 'r2', objectId: 'o2' }],
        },
        { id: 'w2', type: 'opening', side: 'e', offset: 0, width: 1, autoGenerated: true },
      ],
      linkGroup: 'g1',
    });
    _cleanRoomForClipboard(room);
    expect(room.wallObjects).toHaveLength(1);
    expect(room.wallObjects![0].pairedWith).toBeUndefined();
    expect(room.linkGroup).toBeUndefined();
  });
});

describe('computeBoundingBox', () => {
  it('computes BB for rooms', () => {
    const rooms = [makeRoom({ x: 2, y: 3, w: 4, h: 3 })];
    const bb = _computeBoundingBox(ents(rooms));
    expect(bb.minGx).toBe(2);
    expect(bb.minGy).toBe(3);
    expect(bb.maxGx).toBe(6);
    expect(bb.maxGy).toBe(6);
  });

  it('computes BB for polygon rooms', () => {
    const v: [GridPoint, GridPoint, GridPoint, GridPoint] = [
      { gx: 1, gy: 2 },
      { gx: 5, gy: 2 },
      { gx: 6, gy: 4 },
      { gx: 0, gy: 4 },
    ];
    const rooms = [makeRoom({ vertices: v })];
    const bb = _computeBoundingBox(ents(rooms));
    expect(bb.minGx).toBe(0);
    expect(bb.minGy).toBe(2);
    expect(bb.maxGx).toBe(6);
    expect(bb.maxGy).toBe(4);
  });
});

describe('paste with mirror', () => {
  it('horizontal mirror paste flips room position', () => {
    const room = makeRoom({ x: 0, y: 0, w: 2, h: 2 });
    const ec = makeEc([room], [], [], new Set([room.id]));
    copySelection(ec);

    ec.state.mouse = { px: 0, py: 0, gx: 0, gy: 0 };
    pasteClipboard(ec, 'horizontal');

    expect(ec.state.rooms).toHaveLength(2);
    const pasted = ec.state.rooms[1];
    // BB: originGx=0, bbW=2, centerGx=1
    // mirror: x = 2*1 - 0 - 2 = 0 (symmetric)
    expect(pasted.x).toBe(0);
  });

  it('vertical mirror paste flips room position', () => {
    const room = makeRoom({ x: 0, y: 0, w: 4, h: 2 });
    const ec = makeEc([room], [], [], new Set([room.id]));
    copySelection(ec);

    ec.state.mouse = { px: 0, py: 0, gx: 0, gy: 0 };
    pasteClipboard(ec, 'vertical');

    expect(ec.state.rooms).toHaveLength(2);
  });
});
