import type { WallObject, CameraColorPreset } from '../types.ts';
import { CAMERA_COLOR_PRESETS } from '../camera.ts';
import { GRID } from '../grid.ts';
import { hitRoom, isInsideRoom } from '../room.ts';
import { selectSingle, getSingleSelected } from '../selection.ts';
import {
  createWallWindow,
  createWallDoor,
  createWallOpening,
  hitWallObjectInRooms,
  nearestWallSide,
} from '../wall-object.ts';
import {
  createStraightStairs,
  createFoldingStairs,
  createMarker,
  hitInteriorObjectInRooms,
} from '../interior-object.ts';
import { createSecurityCamera } from '../camera.ts';
import { hitFreeText, createFreeText } from '../free-text.ts';
import type { ContextMenuItem } from '../context-menu.ts';
import { bringToFront, sendToBack, bringForward, sendBackward } from '../z-order.ts';
import {
  hasAdjacentPair,
  hasLinkedRoom,
  allAlreadyLinked,
  linkRooms,
  unlinkRooms,
} from '../link.ts';
import {
  syncPairedOpening,
  removePairedOpening,
  isAutoGeneratedOpening,
} from '../adjacency.ts';
import type { EditorContext } from './context.ts';
import { commitChange, applyRoomEdit } from './project.ts';
import { labelDisplayWidth } from './utils.ts';

const CARDINAL_DIRECTIONS: { label: string; dir: 'n' | 'e' | 's' | 'w' }[] = [
  { label: '↑ 上向き', dir: 'n' },
  { label: '→ 右向き', dir: 'e' },
  { label: '↓ 下向き', dir: 's' },
  { label: '← 左向き', dir: 'w' },
];

export function onContextMenu(ec: EditorContext, e: MouseEvent): void {
  e.preventDefault();
  const { state, flags, callbacks } = ec;
  const m = ec.mousePos(e);
  const items: ContextMenuItem[] = [];

  // Check if right-clicking on a FreeText (front layer first, then back)
  const ftHit =
    hitFreeText(state.freeTexts, m.px, m.py, 'front') ||
    hitFreeText(state.freeTexts, m.px, m.py, 'back');
  if (ftHit) {
    const ftId = ftHit.id;
    flags.activeFreeTextId = ftId;
    selectSingle(state.selection, ftId);

    items.push({
      label: 'テキストを変更',
      action: async () => {
        const ft = state.freeTexts.find((f) => f.id === ftId);
        if (!ft) return;
        const result = await callbacks.onFreeTextEdit({ label: ft.label, fontSize: ft.fontSize });
        if (!result) return;
        commitChange(ec, () => {
          const current = state.freeTexts.find((f) => f.id === ftId);
          if (!current) return;
          current.label = result.label;
          current.fontSize = result.fontSize;
        });
      },
    });
    items.push({ separator: true });
    items.push({
      label: ftHit.zLayer === 'front' ? '最背面へ切替' : '最前面へ切替',
      action: () => {
        const ft = state.freeTexts.find((f) => f.id === ftId);
        if (!ft) return;
        commitChange(ec, () => {
          ft.zLayer = ft.zLayer === 'front' ? 'back' : 'front';
        });
      },
    });
    items.push({ separator: true });
    items.push({
      label: 'テキストを削除',
      action: () => {
        commitChange(ec, () => {
          state.freeTexts = state.freeTexts.filter((f) => f.id !== ftId);
        });
        flags.activeFreeTextId = undefined;
      },
    });

    callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
    ec.render();
    return;
  }

  // Check if right-clicking on an interior object
  const intObjHit = hitInteriorObjectInRooms(state.rooms, m.px, m.py);
  if (intObjHit) {
    const roomId = intObjHit.room.id;
    const objId = intObjHit.obj.id;
    flags.activeInteriorObjectId = objId;

    const deleteInteriorObject = (label: string) => {
      items.push({ separator: true });
      items.push({
        label,
        action: () => {
          const room = state.rooms.find((r) => r.id === roomId);
          if (!room) return;
          commitChange(ec, () => {
            room.interiorObjects = room.interiorObjects?.filter((o) => o.id !== objId);
            if (room.interiorObjects?.length === 0) room.interiorObjects = undefined;
          });
          flags.activeInteriorObjectId = undefined;
        },
      });
    };

    if (intObjHit.obj.type === 'stairs') {
      for (const d of CARDINAL_DIRECTIONS) {
        items.push({
          label: d.label,
          disabled: intObjHit.obj.direction === d.dir,
          action: () => {
            const room = state.rooms.find((r) => r.id === roomId);
            if (!room) return;
            const obj = room.interiorObjects?.find((o) => o.id === objId);
            if (!obj || obj.type !== 'stairs') return;
            commitChange(ec, () => {
              obj.direction = d.dir;
            });
          },
        });
      }
      deleteInteriorObject('階段を削除');
    }

    if (intObjHit.obj.type === 'marker') {
      items.push({
        label: 'ラベルを変更',
        action: async () => {
          const room = state.rooms.find((r) => r.id === roomId);
          if (!room) return;
          const obj = room.interiorObjects?.find((o) => o.id === objId);
          if (!obj || obj.type !== 'marker') return;
          const result = await callbacks.onMarkerEdit({ label: obj.label ?? '' });
          if (!result) return;
          commitChange(ec, () => {
            obj.label = result.label || undefined;
          });
        },
      });

      if (intObjHit.obj.markerKind === 'body') {
        items.push({ separator: true });
        for (const d of CARDINAL_DIRECTIONS) {
          items.push({
            label: d.label,
            disabled: intObjHit.obj.direction === d.dir,
            action: () => {
              const room = state.rooms.find((r) => r.id === roomId);
              if (!room) return;
              const obj = room.interiorObjects?.find((o) => o.id === objId);
              if (!obj || obj.type !== 'marker') return;
              commitChange(ec, () => {
                obj.direction = d.dir;
              });
            },
          });
        }
      }

      deleteInteriorObject('マーカーを削除');
    }

    if (intObjHit.obj.type === 'camera') {
      const colorPresets: { label: string; key: CameraColorPreset }[] = [
        { label: '青', key: 'blue' },
        { label: '赤', key: 'red' },
        { label: '緑', key: 'green' },
        { label: '黄', key: 'yellow' },
      ];
      for (const preset of colorPresets) {
        items.push({
          label: `色: ${preset.label}`,
          action: () => {
            const room = state.rooms.find((r) => r.id === roomId);
            if (!room) return;
            const obj = room.interiorObjects?.find((o) => o.id === objId);
            if (!obj || obj.type !== 'camera') return;
            const colors = CAMERA_COLOR_PRESETS[preset.key];
            commitChange(ec, () => {
              obj.fovColor = colors.fovColor;
              obj.fovStrokeColor = colors.fovStrokeColor;
            });
          },
        });
      }
      deleteInteriorObject('カメラを削除');
    }

    callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
    ec.render();
    return;
  }

  // Check if right-clicking on a wall object
  const { viewport } = ec;
  const wallHit = hitWallObjectInRooms(state.rooms, m.px, m.py, viewport.zoom);
  if (wallHit) {
    const roomId = wallHit.room.id;
    const objId = wallHit.obj.id;
    const hitObj = wallHit.obj;

    // 自動生成された開口は操作不可
    if (isAutoGeneratedOpening(hitObj)) {
      items.push({
        label: 'この開口は隣室と連動しています',
        disabled: true,
        action: () => {},
      });
      callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
      return;
    }

    const removeWallObject = () => {
      const room = state.rooms.find((r) => r.id === roomId);
      if (!room) return;
      commitChange(ec, () => {
        const obj = room.wallObjects?.find((o) => o.id === objId);
        if (obj) removePairedOpening(state.rooms, obj);
        room.wallObjects = room.wallObjects?.filter((o) => o.id !== objId);
        if (room.wallObjects?.length === 0) room.wallObjects = undefined;
      });
    };

    if (hitObj.type === 'door') {
      items.push({
        label: '開き方向を切替',
        action: () => {
          const room = state.rooms.find((r) => r.id === roomId);
          if (!room) return;
          const door = room.wallObjects?.find((o) => o.id === objId);
          if (!door || door.type !== 'door') return;
          commitChange(ec, () => {
            door.swing = door.swing === 'inward' ? 'outward' : 'inward';
          });
        },
      });
      items.push({
        label: 'ヒンジ位置を切替',
        action: () => {
          const room = state.rooms.find((r) => r.id === roomId);
          if (!room) return;
          const door = room.wallObjects?.find((o) => o.id === objId);
          if (!door || door.type !== 'door') return;
          commitChange(ec, () => {
            door.hinge = door.hinge === 'start' ? 'end' : 'start';
          });
        },
      });
      items.push({ label: 'ドアを削除', action: removeWallObject });
    } else if (hitObj.type === 'opening') {
      items.push({ label: '開口を削除', action: removeWallObject });
    } else {
      items.push({ label: '窓を削除', action: removeWallObject });
    }

    callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
    return;
  }

  // Check if right-clicking on a room (offer to place window)
  // Prefer the selected room if the click is within it, so that
  // the user can right-click on a room that is behind another one
  // by selecting it first.
  const hitR = hitRoom(state.rooms, m.px, m.py);
  const singleSel = getSingleSelected(state.rooms, state.selection);
  const contextRoom =
    singleSel && hitR && singleSel.id !== hitR.id && isInsideRoom(singleSel, m.px, m.py)
      ? singleSel
      : hitR;
  if (contextRoom) {
    const roomId = contextRoom.id;
    items.push({
      label: '部屋名を変更',
      action: async () => {
        const room = state.rooms.find((r) => r.id === roomId);
        if (!room) return;
        await applyRoomEdit(ec, room);
      },
    });
    items.push({ separator: true });
    const { side, offset } = nearestWallSide(contextRoom, m.px, m.py);
    const hasOverlap = contextRoom.wallObjects?.some(
      (o) => o.side === side && offset < o.offset + o.width && offset + 1 > o.offset,
    );
    const placeWallObject = (factory: () => WallObject) => {
      const room = state.rooms.find((r) => r.id === roomId);
      if (!room) return;
      commitChange(ec, () => {
        if (!room.wallObjects) room.wallObjects = [];
        const obj = factory();
        room.wallObjects.push(obj);
        syncPairedOpening(state.rooms, room, obj);
      });
    };
    items.push({
      label: '窓を配置',
      disabled: hasOverlap ?? false,
      action: () => placeWallObject(() => createWallWindow(side, offset)),
    });
    items.push({
      label: 'ドアを配置',
      disabled: hasOverlap ?? false,
      action: () => placeWallObject(() => createWallDoor(side, offset)),
    });
    items.push({
      label: '開口を配置',
      disabled: hasOverlap ?? false,
      action: () => placeWallObject(() => createWallOpening(side, offset)),
    });

    // Interior object placement
    const canPlaceStraightStairs = contextRoom.w >= 2 && contextRoom.h >= 3;
    const canPlaceFoldingStairs = contextRoom.w >= 4 && contextRoom.h >= 3;
    items.push({ separator: true });
    items.push({
      label: '直線階段を配置',
      disabled: !canPlaceStraightStairs,
      action: () => {
        const room = state.rooms.find((r) => r.id === roomId);
        if (!room) return;
        const sw = 2,
          sh = 3;
        const sx = Math.max(0, Math.min(Math.floor((room.w - sw) / 2), room.w - sw));
        const sy = Math.max(0, Math.min(Math.floor((room.h - sh) / 2), room.h - sh));
        const stairs = createStraightStairs(sx, sy, sw, sh);
        commitChange(ec, () => {
          if (!room.interiorObjects) room.interiorObjects = [];
          room.interiorObjects.push(stairs);
        });
        flags.activeInteriorObjectId = stairs.id;
      },
    });
    items.push({
      label: '折り返し階段を配置',
      disabled: !canPlaceFoldingStairs,
      action: () => {
        const room = state.rooms.find((r) => r.id === roomId);
        if (!room) return;
        const fw = 4,
          fh = 3;
        const fx = Math.max(0, Math.min(Math.floor((room.w - fw) / 2), room.w - fw));
        const fy = Math.max(0, Math.min(Math.floor((room.h - fh) / 2), room.h - fh));
        const stairs = createFoldingStairs(fx, fy, fw, fh);
        commitChange(ec, () => {
          if (!room.interiorObjects) room.interiorObjects = [];
          room.interiorObjects.push(stairs);
        });
        flags.activeInteriorObjectId = stairs.id;
      },
    });

    // マーカー配置: カーソル位置を基準にオブジェクトの左上を決定
    const cursorRelX = m.px / GRID - contextRoom.x;
    const cursorRelY = m.py / GRID - contextRoom.y;

    const canPlaceBodyMarker = contextRoom.w >= 2 && contextRoom.h >= 1;
    items.push({
      label: '死体を配置',
      disabled: !canPlaceBodyMarker,
      action: () => {
        const room = state.rooms.find((r) => r.id === roomId);
        if (!room) return;
        const mw = 2,
          mh = 1;
        const mx = Math.max(0, Math.min(cursorRelX - mw / 2, room.w - mw));
        const my = Math.max(0, Math.min(cursorRelY - mh / 2, room.h - mh));
        const marker = createMarker(mx, my, mw, mh);
        commitChange(ec, () => {
          if (!room.interiorObjects) room.interiorObjects = [];
          room.interiorObjects.push(marker);
        });
        flags.activeInteriorObjectId = marker.id;
      },
    });
    items.push({
      label: 'マーカーを配置',
      action: async () => {
        const room = state.rooms.find((r) => r.id === roomId);
        if (!room) return;
        const result = await callbacks.onMarkerEdit({ label: '' });
        if (!result) return;
        const mw = Math.max(1, Math.min(labelDisplayWidth(result.label), room.w));
        const mh = 1;
        const mx = Math.max(0, Math.min(cursorRelX - mw / 2, room.w - mw));
        const my = Math.max(0, Math.min(cursorRelY - mh / 2, room.h - mh));
        const marker = createMarker(mx, my, mw, mh, 'e', 'pin', result.label || undefined);
        commitChange(ec, () => {
          if (!room.interiorObjects) room.interiorObjects = [];
          room.interiorObjects.push(marker);
        });
        flags.activeInteriorObjectId = marker.id;
      },
    });
    items.push({
      label: 'テキストを配置',
      action: async () => {
        const room = state.rooms.find((r) => r.id === roomId);
        if (!room) return;
        const result = await callbacks.onMarkerEdit({ label: '' });
        if (!result || !result.label) return;
        const mw = Math.max(1, Math.min(labelDisplayWidth(result.label), room.w));
        const mh = 1;
        const mx = Math.max(0, Math.min(cursorRelX - mw / 2, room.w - mw));
        const my = Math.max(0, Math.min(cursorRelY - mh / 2, room.h - mh));
        const marker = createMarker(mx, my, mw, mh, 'e', 'text', result.label);
        commitChange(ec, () => {
          if (!room.interiorObjects) room.interiorObjects = [];
          room.interiorObjects.push(marker);
        });
        flags.activeInteriorObjectId = marker.id;
      },
    });

    // 防犯カメラ配置
    const canPlaceCamera = contextRoom.w >= 1 && contextRoom.h >= 1;
    items.push({
      label: '防犯カメラを配置',
      disabled: !canPlaceCamera,
      action: () => {
        const room = state.rooms.find((r) => r.id === roomId);
        if (!room) return;
        const cw = 1,
          ch = 1;
        const cx = Math.max(0, Math.min(Math.floor(cursorRelX), room.w - cw));
        const cy = Math.max(0, Math.min(Math.floor(cursorRelY), room.h - ch));
        const cam = createSecurityCamera(cx, cy);
        commitChange(ec, () => {
          if (!room.interiorObjects) room.interiorObjects = [];
          room.interiorObjects.push(cam);
        });
        flags.activeInteriorObjectId = cam.id;
      },
    });

    // 連結/連結解除メニュー
    if (
      state.selection.size >= 2 &&
      hasAdjacentPair(state.rooms, state.selection) &&
      !allAlreadyLinked(state.rooms, state.selection)
    ) {
      items.push({ separator: true });
      items.push({
        label: '連結',
        action: () => {
          commitChange(ec, () => {
            linkRooms(state.rooms, state.selection);
          });
        },
      });
    }
    if (hasLinkedRoom(state.rooms, state.selection)) {
      if (items.length > 0 && !('separator' in items[items.length - 1])) {
        items.push({ separator: true });
      }
      items.push({
        label: '連結解除',
        action: () => {
          commitChange(ec, () => {
            unlinkRooms(state.rooms, state.selection);
          });
        },
      });
    }

    const roomIdx = state.rooms.findIndex((r) => r.id === roomId);
    const isFirst = roomIdx === 0;
    const isLast = roomIdx === state.rooms.length - 1;
    items.push({ separator: true });
    items.push({
      label: '最前面へ移動',
      disabled: isLast,
      action: () => commitChange(ec, () => bringToFront(state.rooms, roomId)),
    });
    items.push({
      label: '1つ前面へ移動',
      disabled: isLast,
      action: () => commitChange(ec, () => bringForward(state.rooms, roomId)),
    });
    items.push({
      label: '1つ背面へ移動',
      disabled: isFirst,
      action: () => commitChange(ec, () => sendBackward(state.rooms, roomId)),
    });
    items.push({
      label: '最背面へ移動',
      disabled: isFirst,
      action: () => commitChange(ec, () => sendToBack(state.rooms, roomId)),
    });

    callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
    return;
  }

  // 空白エリアの右クリック: テキストを配置
  items.push({
    label: 'テキストを配置',
    action: async () => {
      const result = await callbacks.onFreeTextEdit({ label: '', fontSize: 14 });
      if (!result || !result.label) return;
      const ft = createFreeText(m.gx, m.gy, result.label, result.fontSize);
      commitChange(ec, () => {
        state.freeTexts.push(ft);
      });
      flags.activeFreeTextId = ft.id;
      selectSingle(state.selection, ft.id);
      ec.render();
    },
  });
  callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
}
