import type {
  WallObject,
  CameraColorPreset,
  FreeText,
  Room,
  RoomInteriorObject,
  MouseCoord,
} from '../types.ts';
import { CAMERA_COLOR_PRESETS } from '../camera.ts';
import { GRID } from '../grid.ts';
import {
  findFreeTextById,
  findInteriorObjectById,
  findRoomById,
  findRoomIndexById,
  findWallObjectById,
} from '../lookup.ts';
import { hitRoom, isInsideRoom } from '../room.ts';
import { rectToVertices } from '../polygon.ts';
import { selectSingle, getSingleSelected } from '../selection.ts';
import {
  createWallWindow,
  createWallDoor,
  createWallOpening,
  hitWallObjectInRooms,
  nearestWallSide,
} from '../wall-object.ts';
import {
  createStraightStairs,
  createFoldingStairs,
  createMarker,
  hitInteriorObjectInRooms,
} from '../interior-object.ts';
import { createSecurityCamera } from '../camera.ts';
import { hitFreeText, createFreeText } from '../free-text.ts';
import { hitFreeStrokeInList, STROKE_HIT_TOLERANCE_PX } from '../free-stroke.ts';
import { hitArrowInList, hitArrowPoint, ARROW_COLOR_PRESETS, ARROW_LINE_WIDTHS } from '../arrow.ts';
import { findArrowById, findFreeStrokeById } from '../lookup.ts';
import type { ContextMenuItem } from '../context-menu.ts';
import { bringToFront, sendToBack, bringForward, sendBackward } from '../z-order.ts';
import {
  hasAdjacentPair,
  hasLinkedRoom,
  allAlreadyLinked,
  linkRooms,
  unlinkRooms,
} from '../link.ts';
import { syncPairedOpening, removePairedOpening, isAutoGeneratedOpening } from '../adjacency.ts';
import type { EditorContext } from './context.ts';
import { commitChange, applyRoomEdit, withFontSizePreview, deleteRoom } from './project.ts';
import { labelDisplayWidth } from './utils.ts';
import { editMarkerViaDialog } from './marker-edit.ts';
import { copySelection, pasteClipboard } from './clipboard.ts';

const CARDINAL_DIRECTIONS: { label: string; dir: 'n' | 'e' | 's' | 'w' }[] = [
  { label: '↑ 上向き', dir: 'n' },
  { label: '→ 右向き', dir: 'e' },
  { label: '↓ 下向き', dir: 's' },
  { label: '← 左向き', dir: 'w' },
];

function buildFreeTextMenu(ec: EditorContext, ftHit: FreeText): ContextMenuItem[] {
  const { state, flags, callbacks } = ec;
  const ftId = ftHit.id;
  flags.activeFreeTextId = ftId;
  selectSingle(state.selection, ftId);

  const items: ContextMenuItem[] = [];
  items.push({
    label: 'テキストを変更',
    action: async () => {
      const ft = findFreeTextById(state.freeTexts, ftId);
      if (!ft) return;
      const findFt = () => findFreeTextById(state.freeTexts, ftId);
      await withFontSizePreview(
        ec,
        () => findFt()?.fontSize,
        (fs) => {
          const current = findFt();
          if (current && fs !== undefined) current.fontSize = fs;
        },
        (onPreview) =>
          callbacks
            .onFreeTextEdit({
              label: ft.label,
              fontSize: ft.fontSize,
              onFontSizePreview: onPreview,
            })
            .then((r) => (r && r.label ? r : null)),
        (result) => {
          const current = findFt();
          if (current) {
            current.label = result.label;
            current.fontSize = result.fontSize;
          }
        },
      );
    },
  });
  items.push({ separator: true });
  items.push({
    label: ftHit.zLayer === 'front' ? '最背面へ切替' : '最前面へ切替',
    action: () => {
      const ft = findFreeTextById(state.freeTexts, ftId);
      if (!ft) return;
      commitChange(ec, () => {
        ft.zLayer = ft.zLayer === 'front' ? 'back' : 'front';
      });
    },
  });
  items.push({ separator: true });
  items.push({
    label: 'テキストを削除',
    action: () => {
      commitChange(ec, () => {
        state.freeTexts = state.freeTexts.filter((f) => f.id !== ftId);
      });
      flags.activeFreeTextId = undefined;
    },
  });
  return items;
}

function buildDirectionItems(
  ec: EditorContext,
  roomId: string,
  objId: string,
  currentDir: 'n' | 'e' | 's' | 'w',
  objType: 'stairs' | 'marker',
): ContextMenuItem[] {
  const { state } = ec;
  return CARDINAL_DIRECTIONS.map((d) => ({
    label: d.label,
    disabled: currentDir === d.dir,
    action: () => {
      const room = findRoomById(state.rooms, roomId);
      if (!room) return;
      const obj = findInteriorObjectById(room, objId);
      if (!obj || obj.type !== objType) return;
      commitChange(ec, () => {
        obj.direction = d.dir;
      });
    },
  }));
}

function buildInteriorObjectMenu(
  ec: EditorContext,
  intObjHit: { room: Room; obj: RoomInteriorObject },
): ContextMenuItem[] {
  const { state, flags } = ec;
  const roomId = intObjHit.room.id;
  const objId = intObjHit.obj.id;
  flags.activeInteriorObjectId = objId;

  const items: ContextMenuItem[] = [];

  const deleteInteriorObject = (label: string) => {
    items.push({ separator: true });
    items.push({
      label,
      action: () => {
        const room = findRoomById(state.rooms, roomId);
        if (!room) return;
        commitChange(ec, () => {
          room.interiorObjects = room.interiorObjects?.filter((o) => o.id !== objId);
          if (room.interiorObjects?.length === 0) room.interiorObjects = undefined;
        });
        flags.activeInteriorObjectId = undefined;
      },
    });
  };

  if (intObjHit.obj.type === 'stairs') {
    items.push(...buildDirectionItems(ec, roomId, objId, intObjHit.obj.direction, 'stairs'));
    deleteInteriorObject('階段を削除');
  }

  if (intObjHit.obj.type === 'marker') {
    items.push({
      label: 'ラベルを変更',
      action: async () => {
        const room = findRoomById(state.rooms, roomId);
        if (!room) return;
        const obj = findInteriorObjectById(room, objId);
        if (!obj || obj.type !== 'marker') return;
        await editMarkerViaDialog(ec, room, obj);
      },
    });

    if (intObjHit.obj.markerKind === 'body') {
      items.push({ separator: true });
      items.push(...buildDirectionItems(ec, roomId, objId, intObjHit.obj.direction, 'marker'));
    }

    deleteInteriorObject('マーカーを削除');
  }

  if (intObjHit.obj.type === 'camera') {
    const colorPresets: { label: string; key: CameraColorPreset }[] = [
      { label: '青', key: 'blue' },
      { label: '赤', key: 'red' },
      { label: '緑', key: 'green' },
      { label: '黄', key: 'yellow' },
    ];
    for (const preset of colorPresets) {
      items.push({
        label: `色: ${preset.label}`,
        action: () => {
          const room = findRoomById(state.rooms, roomId);
          if (!room) return;
          const obj = findInteriorObjectById(room, objId);
          if (!obj || obj.type !== 'camera') return;
          const colors = CAMERA_COLOR_PRESETS[preset.key];
          commitChange(ec, () => {
            obj.fovColor = colors.fovColor;
            obj.fovStrokeColor = colors.fovStrokeColor;
          });
        },
      });
    }
    deleteInteriorObject('カメラを削除');
  }

  return items;
}

function buildWallObjectMenu(
  ec: EditorContext,
  wallHit: { room: Room; obj: WallObject },
): ContextMenuItem[] {
  const { state } = ec;
  const roomId = wallHit.room.id;
  const objId = wallHit.obj.id;
  const hitObj = wallHit.obj;
  const items: ContextMenuItem[] = [];

  // 自動生成された開口は操作不可
  if (isAutoGeneratedOpening(hitObj)) {
    items.push({
      label: 'この開口は隣室と連動しています',
      disabled: true,
      action: () => {},
    });
    return items;
  }

  const removeWallObject = () => {
    const room = findRoomById(state.rooms, roomId);
    if (!room) return;
    commitChange(ec, () => {
      const obj = findWallObjectById(room, objId);
      if (obj) removePairedOpening(state.rooms, obj);
      room.wallObjects = room.wallObjects?.filter((o) => o.id !== objId);
      if (room.wallObjects?.length === 0) room.wallObjects = undefined;
    });
  };

  if (hitObj.type === 'door') {
    items.push({
      label: '開き方向を切替',
      action: () => {
        const room = findRoomById(state.rooms, roomId);
        if (!room) return;
        const door = findWallObjectById(room, objId);
        if (!door || door.type !== 'door') return;
        commitChange(ec, () => {
          door.swing = door.swing === 'inward' ? 'outward' : 'inward';
        });
      },
    });
    items.push({
      label: 'ヒンジ位置を切替',
      action: () => {
        const room = findRoomById(state.rooms, roomId);
        if (!room) return;
        const door = findWallObjectById(room, objId);
        if (!door || door.type !== 'door') return;
        commitChange(ec, () => {
          door.hinge = door.hinge === 'start' ? 'end' : 'start';
        });
      },
    });
    items.push({ label: 'ドアを削除', action: removeWallObject });
  } else if (hitObj.type === 'opening') {
    items.push({ label: '開口を削除', action: removeWallObject });
  } else {
    items.push({ label: '窓を削除', action: removeWallObject });
  }

  return items;
}

function buildRoomMenu(ec: EditorContext, contextRoom: Room, m: MouseCoord): ContextMenuItem[] {
  const { state, flags, callbacks } = ec;
  const roomId = contextRoom.id;
  const items: ContextMenuItem[] = [];

  items.push({
    label: '部屋名を変更',
    action: async () => {
      const room = findRoomById(state.rooms, roomId);
      if (!room) return;
      await applyRoomEdit(ec, room);
    },
  });
  items.push({ separator: true });
  const { side, offset } = nearestWallSide(contextRoom, m.px, m.py);
  const hasOverlap = contextRoom.wallObjects?.some(
    (o) => o.side === side && offset < o.offset + o.width && offset + 1 > o.offset,
  );
  const placeWallObject = (factory: () => WallObject) => {
    const room = findRoomById(state.rooms, roomId);
    if (!room) return;
    commitChange(ec, () => {
      if (!room.wallObjects) room.wallObjects = [];
      const obj = factory();
      room.wallObjects.push(obj);
      syncPairedOpening(state.rooms, room, obj);
    });
  };
  items.push({
    label: '窓を配置',
    disabled: hasOverlap ?? false,
    action: () => placeWallObject(() => createWallWindow(side, offset)),
  });
  items.push({
    label: 'ドアを配置',
    disabled: hasOverlap ?? false,
    action: () => placeWallObject(() => createWallDoor(side, offset)),
  });
  items.push({
    label: '開口を配置',
    disabled: hasOverlap ?? false,
    action: () => placeWallObject(() => createWallOpening(side, offset)),
  });

  // Interior object placement
  const placeInteriorObject = (factory: (room: Room) => RoomInteriorObject) => {
    const room = findRoomById(state.rooms, roomId);
    if (!room) return;
    const obj = factory(room);
    commitChange(ec, () => {
      if (!room.interiorObjects) room.interiorObjects = [];
      room.interiorObjects.push(obj);
    });
    flags.activeInteriorObjectId = obj.id;
  };

  const canPlaceStraightStairs = contextRoom.w >= 2 && contextRoom.h >= 3;
  const canPlaceFoldingStairs = contextRoom.w >= 4 && contextRoom.h >= 3;
  items.push({ separator: true });
  items.push({
    label: '直線階段を配置',
    disabled: !canPlaceStraightStairs,
    action: () => {
      const sw = 2,
        sh = 3;
      placeInteriorObject((room) => {
        const sx = Math.max(0, Math.min(Math.floor((room.w - sw) / 2), room.w - sw));
        const sy = Math.max(0, Math.min(Math.floor((room.h - sh) / 2), room.h - sh));
        return createStraightStairs(sx, sy, sw, sh);
      });
    },
  });
  items.push({
    label: '折り返し階段を配置',
    disabled: !canPlaceFoldingStairs,
    action: () => {
      const fw = 4,
        fh = 3;
      placeInteriorObject((room) => {
        const fx = Math.max(0, Math.min(Math.floor((room.w - fw) / 2), room.w - fw));
        const fy = Math.max(0, Math.min(Math.floor((room.h - fh) / 2), room.h - fh));
        return createFoldingStairs(fx, fy, fw, fh);
      });
    },
  });

  // マーカー配置: カーソル位置を基準にオブジェクトの左上を決定
  const cursorRelX = m.px / GRID - contextRoom.x;
  const cursorRelY = m.py / GRID - contextRoom.y;

  const clampPos = (relCursor: number, size: number, roomSize: number) =>
    Math.max(0, Math.min(relCursor - size / 2, roomSize - size));

  const canPlaceBodyMarker = contextRoom.w >= 2 && contextRoom.h >= 1;
  items.push({
    label: '死体を配置',
    disabled: !canPlaceBodyMarker,
    action: () => {
      const mw = 2,
        mh = 1;
      placeInteriorObject((room) => {
        const mx = clampPos(cursorRelX, mw, room.w);
        const my = clampPos(cursorRelY, mh, room.h);
        return createMarker(mx, my, mw, mh);
      });
    },
  });
  const placeLabeledMarker = (menuLabel: string, markerKind: 'pin' | 'text') => {
    items.push({
      label: menuLabel,
      action: async () => {
        const mh = 1;
        const defaultAutoFontSize = Math.round(mh * GRID * 0.8);
        const result = await callbacks.onMarkerEdit({
          label: '',
          fontSize: undefined,
          autoFontSize: defaultAutoFontSize,
        });
        if (!result) return;
        if (markerKind === 'text' && !result.label) return;
        placeInteriorObject((r) => {
          const mw = Math.max(1, Math.min(labelDisplayWidth(result.label), r.w));
          const mx = clampPos(cursorRelX, mw, r.w);
          const my = clampPos(cursorRelY, mh, r.h);
          const m = createMarker(mx, my, mw, mh, 'e', markerKind, result.label || undefined);
          if (result.fontSize !== undefined) m.fontSize = result.fontSize;
          return m;
        });
      },
    });
  };
  placeLabeledMarker('マーカーを配置', 'pin');
  placeLabeledMarker('テキストを配置', 'text');

  // 防犯カメラ配置
  const canPlaceCamera = contextRoom.w >= 1 && contextRoom.h >= 1;
  items.push({
    label: '防犯カメラを配置',
    disabled: !canPlaceCamera,
    action: () => {
      placeInteriorObject((room) => {
        const cx = Math.max(0, Math.min(Math.floor(cursorRelX), room.w - 1));
        const cy = Math.max(0, Math.min(Math.floor(cursorRelY), room.h - 1));
        return createSecurityCamera(cx, cy);
      });
    },
  });

  // 連結/連結解除メニュー
  if (
    state.selection.size >= 2 &&
    hasAdjacentPair(state.rooms, state.selection) &&
    !allAlreadyLinked(state.rooms, state.selection)
  ) {
    items.push({ separator: true });
    items.push({
      label: '連結',
      action: () => {
        commitChange(ec, () => {
          linkRooms(state.rooms, state.selection);
        });
      },
    });
  }
  if (hasLinkedRoom(state.rooms, state.selection)) {
    if (items.length > 0 && !('separator' in items[items.length - 1])) {
      items.push({ separator: true });
    }
    items.push({
      label: '連結解除',
      action: () => {
        commitChange(ec, () => {
          unlinkRooms(state.rooms, state.selection);
        });
      },
    });
  }

  // 四角形変換メニュー
  items.push({ separator: true });
  if (contextRoom.vertices) {
    items.push({
      label: '矩形に戻す',
      action: () => {
        const room = findRoomById(state.rooms, roomId);
        if (!room) return;
        commitChange(ec, () => {
          delete room.vertices;
        });
      },
    });
  } else {
    items.push({
      label: '四角形に変換',
      action: () => {
        const room = findRoomById(state.rooms, roomId);
        if (!room) return;
        commitChange(ec, () => {
          room.vertices = rectToVertices(room);
        });
      },
    });
  }

  const roomIdx = findRoomIndexById(state.rooms, roomId);
  const isFirst = roomIdx === 0;
  const isLast = roomIdx === state.rooms.length - 1;
  items.push({ separator: true });
  items.push({
    label: '最前面へ移動',
    disabled: isLast,
    action: () => commitChange(ec, () => bringToFront(state.rooms, roomId)),
  });
  items.push({
    label: '1つ前面へ移動',
    disabled: isLast,
    action: () => commitChange(ec, () => bringForward(state.rooms, roomId)),
  });
  items.push({
    label: '1つ背面へ移動',
    disabled: isFirst,
    action: () => commitChange(ec, () => sendBackward(state.rooms, roomId)),
  });
  items.push({
    label: '最背面へ移動',
    disabled: isFirst,
    action: () => commitChange(ec, () => sendToBack(state.rooms, roomId)),
  });

  items.push({ separator: true });
  items.push({
    label: 'コピー',
    action: () => copySelection(ec),
  });

  items.push({ separator: true });
  items.push({
    label: '部屋を削除',
    action: () => deleteRoom(ec, roomId),
  });

  return items;
}

function buildEmptyAreaMenu(ec: EditorContext, m: MouseCoord): ContextMenuItem[] {
  const { state, flags, callbacks } = ec;
  const hasClipboard = flags.clipboard !== null;
  const items: ContextMenuItem[] = [];
  items.push({
    label: 'テキストを配置',
    action: async () => {
      const result = await callbacks.onFreeTextEdit({ label: '', fontSize: 14 });
      if (!result || !result.label) return;
      const ft = createFreeText(m.gx, m.gy, result.label, result.fontSize);
      commitChange(ec, () => {
        state.freeTexts.push(ft);
      });
      flags.activeFreeTextId = ft.id;
      selectSingle(state.selection, ft.id);
      ec.render();
    },
  });
  items.push({ separator: true });
  items.push({
    label: '貼り付け',
    disabled: !hasClipboard,
    action: () => pasteClipboard(ec, 'none', { gx: m.gx, gy: m.gy }),
  });
  items.push({
    label: '左右反転して貼り付け',
    disabled: !hasClipboard,
    action: () => pasteClipboard(ec, 'horizontal', { gx: m.gx, gy: m.gy }),
  });
  items.push({
    label: '上下反転して貼り付け',
    disabled: !hasClipboard,
    action: () => pasteClipboard(ec, 'vertical', { gx: m.gx, gy: m.gy }),
  });
  return items;
}

const STROKE_COLORS = [
  { label: '赤', value: '#ff0000' },
  { label: '青', value: '#0066ff' },
  { label: '緑', value: '#00cc00' },
  { label: '黒', value: '#000000' },
  { label: '白', value: '#ffffff' },
  { label: 'オレンジ', value: '#ff8800' },
  { label: '紫', value: '#9900cc' },
];

const STROKE_WIDTHS = [
  { label: '細 (1px)', value: 1 },
  { label: '普通 (3px)', value: 3 },
  { label: '太 (6px)', value: 6 },
  { label: '極太 (10px)', value: 10 },
];

function buildArrowMenu(
  ec: EditorContext,
  arrowId: string,
  hitGx: number,
  hitGy: number,
): ContextMenuItem[] {
  const { state } = ec;
  const items: ContextMenuItem[] = [];

  // Color change
  for (const c of ARROW_COLOR_PRESETS) {
    items.push({
      label: `色: ${c.label}`,
      action: () => {
        const arrow = findArrowById(state.arrows, arrowId);
        if (!arrow) return;
        commitChange(ec, () => {
          arrow.color = c.value;
        });
      },
    });
  }
  items.push({ separator: true });

  // Line width change
  for (const w of ARROW_LINE_WIDTHS) {
    items.push({
      label: w.label,
      action: () => {
        const arrow = findArrowById(state.arrows, arrowId);
        if (!arrow) return;
        commitChange(ec, () => {
          arrow.lineWidth = w.value;
        });
      },
    });
  }
  items.push({ separator: true });

  // Delete point (if hit on a point and arrow has >2 points)
  const arrow = findArrowById(state.arrows, arrowId);
  if (arrow) {
    const ptIdx = hitArrowPoint(arrow, hitGx, hitGy);
    if (ptIdx !== undefined && arrow.points.length > 2) {
      items.push({
        label: 'ポイントを削除',
        action: () => {
          const a = findArrowById(state.arrows, arrowId);
          if (!a || a.points.length <= 2 || ptIdx >= a.points.length) return;
          commitChange(ec, () => {
            a.points.splice(ptIdx, 1);
          });
        },
      });
      items.push({ separator: true });
    }
  }

  // Label edit
  items.push({
    label: 'ラベルを変更',
    action: () => {
      const a = findArrowById(state.arrows, arrowId);
      if (!a) return;
      const newLabel = prompt('矢印のラベル', a.label ?? '');
      if (newLabel !== null) {
        commitChange(ec, () => {
          a.label = newLabel || undefined;
        });
      }
    },
  });

  items.push({ separator: true });
  items.push({
    label: '矢印を削除',
    action: () => {
      commitChange(ec, () => {
        state.arrows = state.arrows.filter((a) => a.id !== arrowId);
        state.selection.delete(arrowId);
      });
    },
  });
  return items;
}

function buildFreeStrokeMenu(ec: EditorContext, strokeId: string): ContextMenuItem[] {
  const { state } = ec;
  const items: ContextMenuItem[] = [];

  for (const c of STROKE_COLORS) {
    items.push({
      label: `色: ${c.label}`,
      action: () => {
        const stroke = findFreeStrokeById(state.freeStrokes, strokeId);
        if (!stroke) return;
        commitChange(ec, () => {
          stroke.color = c.value;
        });
      },
    });
  }
  items.push({ separator: true });
  for (const w of STROKE_WIDTHS) {
    items.push({
      label: w.label,
      action: () => {
        const stroke = findFreeStrokeById(state.freeStrokes, strokeId);
        if (!stroke) return;
        commitChange(ec, () => {
          stroke.lineWidth = w.value;
        });
      },
    });
  }
  items.push({ separator: true });
  items.push({
    label: 'ストロークを削除',
    action: () => {
      commitChange(ec, () => {
        state.freeStrokes = state.freeStrokes.filter((s) => s.id !== strokeId);
        state.selection.delete(strokeId);
      });
    },
  });
  return items;
}

export function onContextMenu(ec: EditorContext, e: MouseEvent): void {
  e.preventDefault();
  if (ec.state.paintMode) return;
  const { state, callbacks } = ec;
  const m = ec.mousePos(e);

  // Arrow
  {
    const arrowGx = m.px / GRID;
    const arrowGy = m.py / GRID;
    const arrowHit = hitArrowInList(state.arrows, arrowGx, arrowGy);
    if (arrowHit) {
      selectSingle(state.selection, arrowHit.id);
      const items = buildArrowMenu(ec, arrowHit.id, arrowGx, arrowGy);
      callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
      ec.render();
      return;
    }
  }

  // FreeStroke
  const strokeHitTolerance = STROKE_HIT_TOLERANCE_PX / ec.viewport.zoom;
  const strokeHit = hitFreeStrokeInList(state.freeStrokes, m.px, m.py, strokeHitTolerance);
  if (strokeHit) {
    selectSingle(state.selection, strokeHit.id);
    const items = buildFreeStrokeMenu(ec, strokeHit.id);
    callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
    ec.render();
    return;
  }

  // FreeText
  const ftHit =
    hitFreeText(state.freeTexts, m.px, m.py, 'front') ||
    hitFreeText(state.freeTexts, m.px, m.py, 'back');
  if (ftHit) {
    const items = buildFreeTextMenu(ec, ftHit);
    callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
    ec.render();
    return;
  }

  // InteriorObject
  const intObjHit = hitInteriorObjectInRooms(state.rooms, m.px, m.py);
  if (intObjHit) {
    const items = buildInteriorObjectMenu(ec, intObjHit);
    callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
    ec.render();
    return;
  }

  // WallObject
  const { viewport } = ec;
  const wallHit = hitWallObjectInRooms(state.rooms, m.px, m.py, viewport.zoom);
  if (wallHit) {
    const items = buildWallObjectMenu(ec, wallHit);
    callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
    return;
  }

  // Room
  const hitR = hitRoom(state.rooms, m.px, m.py);
  const singleSel = getSingleSelected(state.rooms, state.selection);
  const contextRoom =
    singleSel && hitR && singleSel.id !== hitR.id && isInsideRoom(singleSel, m.px, m.py)
      ? singleSel
      : hitR;
  if (contextRoom) {
    const items = buildRoomMenu(ec, contextRoom, m);
    callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
    return;
  }

  // Empty area
  const items = buildEmptyAreaMenu(ec, m);
  callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
}
