import type { EditorState } from '../types.ts';
import type { ViewportState } from '../viewport.ts';
import { loadFromStorage, loadViewport } from '../persistence.ts';
import { syncAllPairedOpenings } from '../adjacency.ts';
import type {
  EditorCallbacks,
  EditorAPI,
  EditorContext,
  RoomEditData,
  MarkerEditData,
  ContextMenuRequest,
} from './context.ts';
import { createMousePos } from './utils.ts';
import { render } from './render.ts';
import {
  commitChange as commitChangeFn,
  undo,
  newProject,
  loadProjectData,
  saveProject,
  exportAsPng,
} from './project.ts';
import { onWheel } from './wheel.ts';
import { onKeyDown, onKeyUp } from './keyboard.ts';
import { onDblClick } from './dblclick.ts';
import { onMouseDown } from './mouse-down.ts';
import { onMouseMove } from './mouse-move.ts';
import { onMouseUp } from './mouse-up.ts';
import { onContextMenu } from './context-menu-handler.ts';

export type { EditorAPI, RoomEditData, MarkerEditData, ContextMenuRequest };

export function initEditor(
  canvas: HTMLCanvasElement,
  container: HTMLElement,
  callbacks: EditorCallbacks,
): EditorAPI {
  const ctx = canvas.getContext('2d')!;

  const state: EditorState = {
    rooms: [],
    freeTexts: [],
    selection: new Set(),
    history: [],
    drag: null,
    mouse: { px: 0, py: 0, gx: 0, gy: 0 },
  };

  const viewport: ViewportState = { zoom: 1, panX: 0, panY: 0 };
  const flags: EditorContext['flags'] = {
    isPanning: false,
    activeInteriorObjectId: undefined,
    activeFreeTextId: undefined,
  };

  const mousePos = createMousePos(canvas, viewport);

  const ec: EditorContext = {
    canvas,
    ctx,
    container,
    state,
    viewport,
    callbacks,
    flags,
    render: () => render(ec),
    commitChange: (fn) => commitChangeFn(ec, fn),
    mousePos,
  };

  function resizeCanvas(): void {
    canvas.width = container.clientWidth;
    canvas.height = container.clientHeight;
    ec.render();
  }

  // Initialize
  resizeCanvas();
  const loaded = loadFromStorage();
  state.rooms = loaded.rooms;
  state.freeTexts = loaded.freeTexts;
  if (loaded.warning) {
    // setTimeout で描画初期化完了後に表示（alert はレンダリングをブロックするため）
    setTimeout(() => alert(loaded.warning), 0);
  }
  // 旧データにautoGeneratedフラグがない可能性があるため、ロード時にペア開口を再構築
  syncAllPairedOpenings(state.rooms);

  const saved = loadViewport();
  if (saved) {
    viewport.zoom = saved.zoom;
    viewport.panX = saved.panX;
    viewport.panY = saved.panY;
  }

  // Event handlers bound to ec
  const handleMouseDown = (e: MouseEvent) => onMouseDown(ec, e);
  const handleMouseMove = (e: MouseEvent) => onMouseMove(ec, e);
  const handleMouseUp = (e: MouseEvent) => onMouseUp(ec, e);
  const handleDblClick = (e: MouseEvent) => {
    onDblClick(ec, e).catch(console.error);
  };
  const handleContextMenu = (e: MouseEvent) => onContextMenu(ec, e);
  const handleKeyDown = (e: KeyboardEvent) => onKeyDown(ec, e);
  const handleKeyUp = (e: KeyboardEvent) => onKeyUp(ec, e);
  const handleWheel = (e: WheelEvent) => onWheel(ec, e);

  canvas.addEventListener('mousedown', handleMouseDown);
  canvas.addEventListener('mousemove', handleMouseMove);
  document.addEventListener('mouseup', handleMouseUp);
  canvas.addEventListener('dblclick', handleDblClick);
  canvas.addEventListener('contextmenu', handleContextMenu);
  document.addEventListener('keydown', handleKeyDown);
  document.addEventListener('keyup', handleKeyUp);
  canvas.addEventListener('wheel', handleWheel, { passive: false });

  ec.render();

  return {
    undo: () => undo(ec),
    newProject: () => newProject(ec),
    loadProject: (data) => loadProjectData(ec, data),
    saveProject: () => saveProject(ec),
    exportAsPng: () => exportAsPng(ec),
    resize: resizeCanvas,
    destroy() {
      canvas.removeEventListener('mousedown', handleMouseDown);
      canvas.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleMouseUp);
      canvas.removeEventListener('dblclick', handleDblClick);
      canvas.removeEventListener('contextmenu', handleContextMenu);
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('keyup', handleKeyUp);
      canvas.removeEventListener('wheel', handleWheel);
    },
  };
}
