import type { EditorState, MouseCoord, Room, WallObject } from './types.ts';
import { GRID, drawGrid } from './grid.ts';
import {
  drawRoom,
  drawCreationPreview,
  hitHandle,
  hitRoom,
  isInsideRoom,
  createRoom,
  calcAutoFontSize,
  computeRoomsBoundingBox,
} from './room.ts';
import { toggleSelection, selectSingle, clearSelection, getSingleSelected } from './selection.ts';
import { pushUndo, popUndo } from './history.ts';
import {
  persistToStorage,
  loadFromStorage,
  exportPng,
  saveAsJson,
  persistViewport,
  loadViewport,
} from './persistence.ts';
import {
  screenToWorld,
  zoomAtPoint,
  zoomAtCenter as zoomAtCenterFn,
  ZOOM_STEP,
  type ViewportState,
} from './viewport.ts';
import {
  createWallWindow,
  createWallDoor,
  createWallOpening,
  hitWallObjectInRooms,
  hitWallObjectEdgeInRooms,
  nearestWallSide,
  clampWallObjects,
  computeWallObjectPosition,
  computeWallObjectResize,
  drawOutwardDoorsOverlay,
} from './wall-object.ts';
import type { ContextMenuItem } from './context-menu.ts';
import { bringToFront, sendToBack, bringForward, sendBackward } from './z-order.ts';
import {
  expandWithLinked,
  linkRooms,
  unlinkRooms,
  cleanupSingletonGroups,
  hasAdjacentPair,
  hasLinkedRoom,
  allAlreadyLinked,
} from './link.ts';
import {
  syncPairedOpening,
  removePairedOpening,
  syncAllPairedOpenings,
  isAutoGeneratedOpening,
} from './adjacency.ts';

export interface RoomEditData {
  label: string;
  fontSize: number | undefined;
  autoFontSize: number;
}

export interface ContextMenuRequest {
  screenX: number;
  screenY: number;
  items: ContextMenuItem[];
}

export interface EditorCallbacks {
  onStatusChange: (text: string) => void;
  onRoomEdit: (data: RoomEditData) => Promise<{ label: string; fontSize?: number } | null>;
  onContextMenu: (request: ContextMenuRequest) => void;
}

export interface EditorAPI {
  undo: () => void;
  newProject: () => void;
  loadProject: (rooms: Room[]) => void;
  saveProject: () => void;
  exportAsPng: () => void;
  resize: () => void;
  destroy: () => void;
}

export function initEditor(
  canvas: HTMLCanvasElement,
  container: HTMLElement,
  callbacks: EditorCallbacks,
): EditorAPI {
  const ctx = canvas.getContext('2d')!;

  const state: EditorState = {
    rooms: [],
    selection: new Set(),
    history: [],
    drag: null,
    mouse: { px: 0, py: 0, gx: 0, gy: 0 },
  };

  const viewport: ViewportState = { zoom: 1, panX: 0, panY: 0 };
  let isPanning = false;

  function mousePos(e: MouseEvent): MouseCoord {
    const rect = canvas.getBoundingClientRect();
    const sx = e.clientX - rect.left;
    const sy = e.clientY - rect.top;
    const { px, py } = screenToWorld(sx, sy, viewport);
    return { px, py, gx: Math.round(px / GRID), gy: Math.round(py / GRID) };
  }

  function render(): void {
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.fillStyle = '#fff';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    ctx.setTransform(
      viewport.zoom,
      0,
      0,
      viewport.zoom,
      -viewport.panX * viewport.zoom,
      -viewport.panY * viewport.zoom,
    );

    const viewMinX = viewport.panX;
    const viewMinY = viewport.panY;
    const viewMaxX = viewport.panX + canvas.width / viewport.zoom;
    const viewMaxY = viewport.panY + canvas.height / viewport.zoom;
    drawGrid(ctx, viewMinX, viewMinY, viewMaxX, viewMaxY);

    const activeWallObjectId =
      state.drag?.type === 'moveWallObject' || state.drag?.type === 'resizeWallObject'
        ? state.drag.objectId
        : undefined;
    for (const r of state.rooms) {
      const isSelected = state.selection.has(r.id);
      drawRoom(
        ctx,
        r,
        isSelected,
        isSelected && state.selection.size === 1,
        viewport.zoom,
        activeWallObjectId,
      );
    }

    // 2nd pass: redraw outward doors on top of all rooms to prevent occlusion
    for (const r of state.rooms) {
      const isSelected = state.selection.has(r.id);
      drawOutwardDoorsOverlay(ctx, r, isSelected, viewport.zoom, activeWallObjectId);
    }

    if (state.drag && state.drag.type === 'create') {
      drawCreationPreview(ctx, state.drag.start, state.drag.cur, viewport.zoom);
    }

    ctx.setTransform(1, 0, 0, 1, 0, 0);
    updateStatus();
  }

  /* eslint-disable no-irregular-whitespace */
  function updateStatus(): void {
    const zoomPct = Math.round(viewport.zoom * 100);
    let text = `(${state.mouse.gx}, ${state.mouse.gy})　部屋: ${state.rooms.length}　|　${zoomPct}%`;
    if (state.selection.size === 1) {
      const sel = getSingleSelected(state.rooms, state.selection);
      if (sel) {
        text += `　|　${sel.label || '(名前なし)'}　${sel.w}×${sel.h}`;
      }
    } else if (state.selection.size > 1) {
      text += `　|　${state.selection.size}個選択中`;
    }
    callbacks.onStatusChange(text);
  }
  /* eslint-enable no-irregular-whitespace */

  function commitChange(fn: () => void): void {
    pushUndo(state.history, state.rooms);
    fn();
    render();
    persistToStorage(state.rooms);
  }

  function undo(): void {
    const restored = popUndo(state.history);
    if (!restored) return;
    state.rooms = restored;
    clearSelection(state.selection);
    render();
    persistToStorage(state.rooms);
  }

  function newProject(): void {
    if (state.rooms.length && !confirm('現在の間取り図をクリアしますか？')) return;
    commitChange(() => {
      state.rooms = [];
      clearSelection(state.selection);
    });
  }

  function loadProjectData(rooms: Room[]): void {
    commitChange(() => {
      state.rooms = rooms;
      clearSelection(state.selection);
      syncAllPairedOpenings(state.rooms);
    });
  }

  function saveProject(): void {
    saveAsJson(state.rooms);
  }

  function exportAsPng(): void {
    const prevSelection = new Set(state.selection);
    clearSelection(state.selection);

    const savedViewport = { ...viewport };
    const savedW = canvas.width;
    const savedH = canvas.height;

    try {
      const bbox = computeRoomsBoundingBox(state.rooms);
      const maxDim = Math.max(bbox.w, bbox.h);
      const MAX_EXPORT_SIZE = 16384;
      const exportScale = maxDim > MAX_EXPORT_SIZE ? MAX_EXPORT_SIZE / maxDim : 1;
      if (exportScale < 1) {
        console.warn(
          `PNG export: サイズが上限を超えたため縮小されます (${Math.round(maxDim)}px → ${MAX_EXPORT_SIZE}px)`,
        );
      }
      viewport.zoom = exportScale;
      viewport.panX = bbox.x;
      viewport.panY = bbox.y;
      canvas.width = Math.max(1, Math.round(bbox.w * exportScale));
      canvas.height = Math.max(1, Math.round(bbox.h * exportScale));

      render();
      exportPng(canvas);
    } finally {
      canvas.width = savedW;
      canvas.height = savedH;
      Object.assign(viewport, savedViewport);
      for (const id of prevSelection) state.selection.add(id);
      render();
    }
  }

  function onMouseDown(e: MouseEvent): void {
    if (e.button === 1 || (e.button === 0 && isPanning)) {
      e.preventDefault();
      const rect = canvas.getBoundingClientRect();
      state.drag = {
        type: 'pan',
        startScreenX: e.clientX - rect.left,
        startScreenY: e.clientY - rect.top,
        startPanX: viewport.panX,
        startPanY: viewport.panY,
      };
      canvas.style.cursor = 'grabbing';
      return;
    }

    const m = mousePos(e);
    const shift = e.shiftKey;

    // Check wall object edge hit (resize) FIRST — on narrow walls, room handles overlap
    const selectedRooms = state.rooms.filter((r) => state.selection.has(r.id));
    const edgeHit = hitWallObjectEdgeInRooms(selectedRooms, m.px, m.py, viewport.zoom, true);
    if (edgeHit) {
      pushUndo(state.history, state.rooms);
      const horiz = edgeHit.obj.side === 'n' || edgeHit.obj.side === 's';
      state.drag = {
        type: 'resizeWallObject',
        roomId: edgeHit.room.id,
        objectId: edgeHit.obj.id,
        edge: edgeHit.edge,
        origOffset: edgeHit.obj.offset,
        origWidth: edgeHit.obj.width,
      };
      canvas.style.cursor = horiz ? 'ew-resize' : 'ns-resize';
      render();
      return;
    }

    const handleHit = hitHandle(state.rooms, state.selection, m.px, m.py, viewport.zoom);
    if (handleHit) {
      pushUndo(state.history, state.rooms);
      const { handle, room } = handleHit;
      state.drag = {
        type: 'resize',
        dir: handle.dir,
        orig: { x: room.x, y: room.y, w: room.w, h: room.h },
        targetId: room.id,
        start: m,
      };
      return;
    }

    // Check wall object hit (window drag) — skip auto-generated openings
    const wallHit = hitWallObjectInRooms(state.rooms, m.px, m.py, viewport.zoom, true);
    if (wallHit) {
      pushUndo(state.history, state.rooms);
      state.drag = {
        type: 'moveWallObject',
        roomId: wallHit.room.id,
        objectId: wallHit.obj.id,
      };
      canvas.style.cursor = 'grabbing';
      render();
      return;
    }

    const r = hitRoom(state.rooms, m.px, m.py);
    if (r) {
      if (shift) {
        toggleSelection(state.selection, r.id);
      } else {
        if (!state.selection.has(r.id)) {
          selectSingle(state.selection, r.id);
        }
      }
      if (state.selection.size === 0) {
        render();
        return;
      }
      pushUndo(state.history, state.rooms);
      const expanded = expandWithLinked(state.rooms, state.selection);
      const originals = new Map<string, { x: number; y: number }>();
      for (const room of state.rooms) {
        if (expanded.has(room.id)) {
          originals.set(room.id, { x: room.x, y: room.y });
        }
      }
      state.drag = { type: 'move', originals, start: m };
      render();
      return;
    }

    if (!shift) clearSelection(state.selection);
    state.drag = { type: 'create', start: m, cur: m };
    render();
  }

  function onMouseMove(e: MouseEvent): void {
    if (state.drag && state.drag.type === 'pan') {
      const rect = canvas.getBoundingClientRect();
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;
      viewport.panX = state.drag.startPanX - (sx - state.drag.startScreenX) / viewport.zoom;
      viewport.panY = state.drag.startPanY - (sy - state.drag.startScreenY) / viewport.zoom;
      state.mouse = mousePos(e);
      render();
      return;
    }

    const m = mousePos(e);
    state.mouse = m;

    if (!state.drag) {
      if (isPanning) {
        canvas.style.cursor = 'grab';
        updateStatus();
        return;
      }
      const selectedRooms = state.rooms.filter((r) => state.selection.has(r.id));
      const edgeHover = hitWallObjectEdgeInRooms(selectedRooms, m.px, m.py, viewport.zoom, true);
      if (edgeHover) {
        const horiz = edgeHover.obj.side === 'n' || edgeHover.obj.side === 's';
        canvas.style.cursor = horiz ? 'ew-resize' : 'ns-resize';
      } else {
        const h = hitHandle(state.rooms, state.selection, m.px, m.py, viewport.zoom);
        if (h) {
          canvas.style.cursor = h.handle.dir + '-resize';
        } else if (hitWallObjectInRooms(state.rooms, m.px, m.py, viewport.zoom, true)) {
          canvas.style.cursor = 'grab';
        } else if (hitRoom(state.rooms, m.px, m.py)) {
          canvas.style.cursor = 'move';
        } else {
          canvas.style.cursor = 'crosshair';
        }
      }
      updateStatus();
      return;
    }

    if (state.drag.type === 'create') {
      state.drag.cur = m;
    } else if (state.drag.type === 'move') {
      const dx = m.gx - state.drag.start.gx;
      const dy = m.gy - state.drag.start.gy;
      for (const [id, orig] of state.drag.originals) {
        const room = state.rooms.find((r) => r.id === id);
        if (room) {
          room.x = orig.x + dx;
          room.y = orig.y + dy;
        }
      }
    } else if (state.drag.type === 'resize') {
      const o = state.drag.orig;
      const d = state.drag.dir;
      const targetId = state.drag.targetId;
      const target = state.rooms.find((r) => r.id === targetId);
      if (target) {
        if (d.includes('w')) {
          target.x = Math.min(m.gx, o.x + o.w - 1);
          target.w = Math.max(1, o.x + o.w - target.x);
        }
        if (d.includes('e')) {
          target.w = Math.max(1, m.gx - o.x);
        }
        if (d.includes('n')) {
          target.y = Math.min(m.gy, o.y + o.h - 1);
          target.h = Math.max(1, o.y + o.h - target.y);
        }
        if (d.includes('s')) {
          target.h = Math.max(1, m.gy - o.y);
        }
        clampWallObjects(target);
      }
    } else if (state.drag.type === 'moveWallObject') {
      const drag = state.drag;
      const targetRoom = state.rooms.find((r) => r.id === drag.roomId);
      if (targetRoom) {
        const obj = targetRoom.wallObjects?.find((o) => o.id === drag.objectId);
        if (obj) {
          const pos = computeWallObjectPosition(targetRoom, m.px, m.py, obj.width);
          obj.side = pos.side;
          obj.offset = pos.offset;
          // NOTE: 毎mousemoveで呼ぶためパフォーマンスコストがある。
          // 部屋数が非常に多い間取りでは、デバウンスやmouseup時のみの同期を検討。
          syncPairedOpening(state.rooms, targetRoom, obj);
        }
      }
    } else if (state.drag.type === 'resizeWallObject') {
      const drag = state.drag;
      const targetRoom = state.rooms.find((r) => r.id === drag.roomId);
      if (targetRoom) {
        const obj = targetRoom.wallObjects?.find((o) => o.id === drag.objectId);
        if (obj) {
          const result = computeWallObjectResize(
            targetRoom,
            obj,
            drag.edge,
            m.px,
            m.py,
            drag.origOffset,
            drag.origWidth,
          );
          obj.offset = result.offset;
          obj.width = result.width;
          // NOTE: 毎mousemoveで呼ぶためパフォーマンスコストがある。
          // 部屋数が非常に多い間取りでは、デバウンスやmouseup時のみの同期を検討。
          syncPairedOpening(state.rooms, targetRoom, obj);
        }
      }
    }

    render();
  }

  function onMouseUp(e: MouseEvent): void {
    if (!state.drag) return;

    if (state.drag.type === 'pan') {
      state.drag = null;
      canvas.style.cursor = isPanning ? 'grab' : 'crosshair';
      persistViewport(viewport);
      return;
    }

    if (state.drag.type === 'moveWallObject' || state.drag.type === 'resizeWallObject') {
      const dragRoomId = state.drag.roomId;
      const dragObjId = state.drag.objectId;
      selectSingle(state.selection, dragRoomId);
      state.drag = null;
      // 壁オブジェクトの同期
      const dragRoom = state.rooms.find((r) => r.id === dragRoomId);
      const dragObj = dragRoom?.wallObjects?.find((o) => o.id === dragObjId);
      if (dragRoom && dragObj) {
        syncPairedOpening(state.rooms, dragRoom, dragObj);
      }
      // Cursor will be recalculated on next mousemove; set a reasonable default
      const m = mousePos(e);
      const stillOnWallObj = hitWallObjectInRooms(state.rooms, m.px, m.py, viewport.zoom, true);
      canvas.style.cursor = stillOnWallObj ? 'grab' : 'crosshair';
      render();
      persistToStorage(state.rooms);
      return;
    }

    if (state.drag.type === 'create') {
      const m = mousePos(e);
      const x = Math.min(state.drag.start.gx, m.gx);
      const y = Math.min(state.drag.start.gy, m.gy);
      const w = Math.abs(m.gx - state.drag.start.gx);
      const h = Math.abs(m.gy - state.drag.start.gy);
      if (w > 0 && h > 0) {
        pushUndo(state.history, state.rooms);
        const room = createRoom(x, y, w, h);
        state.rooms.push(room);
        clearSelection(state.selection);
        state.selection.add(room.id);
      }
    } else if (state.drag.type === 'move' || state.drag.type === 'resize') {
      // 部屋の移動・リサイズ後にペア開口を再同期
      syncAllPairedOpenings(state.rooms);
    }

    state.drag = null;
    render();
    persistToStorage(state.rooms);
  }

  function onContextMenu(e: MouseEvent): void {
    e.preventDefault();
    const m = mousePos(e);
    const items: ContextMenuItem[] = [];

    // Check if right-clicking on a wall object
    const wallHit = hitWallObjectInRooms(state.rooms, m.px, m.py, viewport.zoom);
    if (wallHit) {
      const roomId = wallHit.room.id;
      const objId = wallHit.obj.id;
      const hitObj = wallHit.obj;

      // 自動生成された開口は操作不可
      if (isAutoGeneratedOpening(hitObj)) {
        items.push({
          label: 'この開口は隣室と連動しています',
          disabled: true,
          action: () => {},
        });
        callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
        return;
      }

      const removeWallObject = () => {
        const room = state.rooms.find((r) => r.id === roomId);
        if (!room) return;
        commitChange(() => {
          const obj = room.wallObjects?.find((o) => o.id === objId);
          if (obj) removePairedOpening(state.rooms, obj);
          room.wallObjects = room.wallObjects?.filter((o) => o.id !== objId);
          if (room.wallObjects?.length === 0) room.wallObjects = undefined;
        });
      };

      if (hitObj.type === 'door') {
        items.push({
          label: '開き方向を切替',
          action: () => {
            const room = state.rooms.find((r) => r.id === roomId);
            if (!room) return;
            const door = room.wallObjects?.find((o) => o.id === objId);
            if (!door || door.type !== 'door') return;
            commitChange(() => {
              door.swing = door.swing === 'inward' ? 'outward' : 'inward';
            });
          },
        });
        items.push({ label: 'ドアを削除', action: removeWallObject });
      } else if (hitObj.type === 'opening') {
        items.push({ label: '開口を削除', action: removeWallObject });
      } else {
        items.push({ label: '窓を削除', action: removeWallObject });
      }

      callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
      return;
    }

    // Check if right-clicking on a room (offer to place window)
    // Prefer the selected room if the click is within it, so that
    // the user can right-click on a room that is behind another one
    // by selecting it first.
    const hitR = hitRoom(state.rooms, m.px, m.py);
    const singleSel = getSingleSelected(state.rooms, state.selection);
    const contextRoom =
      singleSel && hitR && singleSel.id !== hitR.id && isInsideRoom(singleSel, m.px, m.py)
        ? singleSel
        : hitR;
    if (contextRoom) {
      const roomId = contextRoom.id;
      const { side, offset } = nearestWallSide(contextRoom, m.px, m.py);
      const hasOverlap = contextRoom.wallObjects?.some(
        (o) => o.side === side && offset < o.offset + o.width && offset + 1 > o.offset,
      );
      const placeWallObject = (factory: () => WallObject) => {
        const room = state.rooms.find((r) => r.id === roomId);
        if (!room) return;
        commitChange(() => {
          if (!room.wallObjects) room.wallObjects = [];
          const obj = factory();
          room.wallObjects.push(obj);
          syncPairedOpening(state.rooms, room, obj);
        });
      };
      items.push({
        label: '窓を配置',
        disabled: hasOverlap ?? false,
        action: () => placeWallObject(() => createWallWindow(side, offset)),
      });
      items.push({
        label: 'ドアを配置',
        disabled: hasOverlap ?? false,
        action: () => placeWallObject(() => createWallDoor(side, offset)),
      });
      items.push({
        label: '開口を配置',
        disabled: hasOverlap ?? false,
        action: () => placeWallObject(() => createWallOpening(side, offset)),
      });

      // 連結/連結解除メニュー
      if (
        state.selection.size >= 2 &&
        hasAdjacentPair(state.rooms, state.selection) &&
        !allAlreadyLinked(state.rooms, state.selection)
      ) {
        items.push({ separator: true });
        items.push({
          label: '連結',
          action: () => {
            commitChange(() => {
              linkRooms(state.rooms, state.selection);
            });
          },
        });
      }
      if (hasLinkedRoom(state.rooms, state.selection)) {
        if (items.length > 0 && !('separator' in items[items.length - 1])) {
          items.push({ separator: true });
        }
        items.push({
          label: '連結解除',
          action: () => {
            commitChange(() => {
              unlinkRooms(state.rooms, state.selection);
            });
          },
        });
      }

      const roomIdx = state.rooms.findIndex((r) => r.id === roomId);
      const isFirst = roomIdx === 0;
      const isLast = roomIdx === state.rooms.length - 1;
      items.push({ separator: true });
      items.push({
        label: '最前面へ移動',
        disabled: isLast,
        action: () => commitChange(() => bringToFront(state.rooms, roomId)),
      });
      items.push({
        label: '1つ前面へ移動',
        disabled: isLast,
        action: () => commitChange(() => bringForward(state.rooms, roomId)),
      });
      items.push({
        label: '1つ背面へ移動',
        disabled: isFirst,
        action: () => commitChange(() => sendBackward(state.rooms, roomId)),
      });
      items.push({
        label: '最背面へ移動',
        disabled: isFirst,
        action: () => commitChange(() => sendToBack(state.rooms, roomId)),
      });

      callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
    }
  }

  async function onDblClick(e: MouseEvent): Promise<void> {
    const m = mousePos(e);
    const r = hitRoom(state.rooms, m.px, m.py);
    if (r) {
      const result = await callbacks.onRoomEdit({
        label: r.label || '',
        fontSize: r.fontSize,
        autoFontSize: Math.round(calcAutoFontSize(r)),
      });
      if (result) {
        commitChange(() => {
          r.label = result.label;
          r.fontSize = result.fontSize;
        });
      }
    }
  }

  function onKeyDown(e: KeyboardEvent): void {
    if (e.code === 'Space' && !isPanning && document.activeElement === document.body) {
      e.preventDefault();
      isPanning = true;
      canvas.style.cursor = 'grab';
      return;
    }

    if ((e.metaKey || e.ctrlKey) && (e.key === '=' || e.key === '+')) {
      e.preventDefault();
      const newVp = zoomAtCenterFn(viewport, canvas.width, canvas.height, viewport.zoom * 1.25);
      Object.assign(viewport, newVp);
      render();
      persistViewport(viewport);
      return;
    }
    if ((e.metaKey || e.ctrlKey) && e.key === '-') {
      e.preventDefault();
      const newVp = zoomAtCenterFn(viewport, canvas.width, canvas.height, viewport.zoom / 1.25);
      Object.assign(viewport, newVp);
      render();
      persistViewport(viewport);
      return;
    }
    if ((e.metaKey || e.ctrlKey) && e.key === '0') {
      e.preventDefault();
      viewport.zoom = 1;
      viewport.panX = 0;
      viewport.panY = 0;
      render();
      persistViewport(viewport);
      return;
    }

    if (
      (e.metaKey || e.ctrlKey) &&
      (e.key === ']' || e.key === '[') &&
      state.selection.size === 1
    ) {
      e.preventDefault();
      const roomId = [...state.selection][0];
      const forward = e.key === ']';
      const fn = e.shiftKey
        ? forward
          ? bringToFront
          : sendToBack
        : forward
          ? bringForward
          : sendBackward;
      pushUndo(state.history, state.rooms);
      const changed = fn(state.rooms, roomId);
      if (changed) {
        render();
        persistToStorage(state.rooms);
      } else {
        state.history.pop();
      }
      return;
    }

    if (
      (e.key === 'Delete' || e.key === 'Backspace') &&
      state.selection.size > 0 &&
      document.activeElement === document.body
    ) {
      e.preventDefault();
      commitChange(() => {
        state.rooms = state.rooms.filter((r) => !state.selection.has(r.id));
        cleanupSingletonGroups(state.rooms);
        syncAllPairedOpenings(state.rooms);
        clearSelection(state.selection);
      });
    }
    if ((e.metaKey || e.ctrlKey) && e.key === 'z') {
      e.preventDefault();
      undo();
    }
  }

  function onKeyUp(e: KeyboardEvent): void {
    if (e.code === 'Space') {
      isPanning = false;
      if (!state.drag || state.drag.type !== 'pan') {
        canvas.style.cursor = 'crosshair';
      }
    }
  }

  function onWheel(e: WheelEvent): void {
    e.preventDefault();
    if (state.drag && state.drag.type !== 'pan') return;

    if (e.ctrlKey) {
      const rect = canvas.getBoundingClientRect();
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;

      const factor = e.deltaY < 0 ? ZOOM_STEP : 1 / ZOOM_STEP;
      const newVp = zoomAtPoint(viewport, sx, sy, viewport.zoom * factor);

      if (newVp.zoom === viewport.zoom) return;

      Object.assign(viewport, newVp);
    } else {
      viewport.panX += e.deltaX / viewport.zoom;
      viewport.panY += e.deltaY / viewport.zoom;
    }

    render();
    persistViewport(viewport);
  }

  function resizeCanvas(): void {
    canvas.width = container.clientWidth;
    canvas.height = container.clientHeight;
    render();
  }

  // Initialize
  resizeCanvas();
  state.rooms = loadFromStorage();
  // 旧データにautoGeneratedフラグがない可能性があるため、ロード時にペア開口を再構築
  syncAllPairedOpenings(state.rooms);

  const saved = loadViewport();
  if (saved) {
    viewport.zoom = saved.zoom;
    viewport.panX = saved.panX;
    viewport.panY = saved.panY;
  }

  canvas.addEventListener('mousedown', onMouseDown);
  canvas.addEventListener('mousemove', onMouseMove);
  document.addEventListener('mouseup', onMouseUp);
  canvas.addEventListener('dblclick', onDblClick);
  canvas.addEventListener('contextmenu', onContextMenu);
  document.addEventListener('keydown', onKeyDown);
  document.addEventListener('keyup', onKeyUp);
  canvas.addEventListener('wheel', onWheel, { passive: false });

  render();

  return {
    undo,
    newProject,
    loadProject: loadProjectData,
    saveProject,
    exportAsPng,
    resize: resizeCanvas,
    destroy() {
      canvas.removeEventListener('mousedown', onMouseDown);
      canvas.removeEventListener('mousemove', onMouseMove);
      document.removeEventListener('mouseup', onMouseUp);
      canvas.removeEventListener('dblclick', onDblClick);
      canvas.removeEventListener('contextmenu', onContextMenu);
      document.removeEventListener('keydown', onKeyDown);
      document.removeEventListener('keyup', onKeyUp);
      canvas.removeEventListener('wheel', onWheel);
    },
  };
}
