import type {
  EditorState,
  MouseCoord,
  Room,
  FreeText,
  FreeTextEditData,
  WallObject,
} from './types.ts';
import { GRID, drawGrid } from './grid.ts';
import {
  drawRoom,
  drawCreationPreview,
  drawAreaSelectPreview,
  hitHandle,
  hitRoom,
  isInsideRoom,
  createRoom,
  calcAutoFontSize,
  computeRoomsBoundingBox,
  findRoomsInArea,
  normalizeArea,
} from './room.ts';
import { toggleSelection, selectSingle, clearSelection, getSingleSelected } from './selection.ts';
import { pushUndo, popUndo } from './history.ts';
import {
  persistToStorage,
  loadFromStorage,
  exportPng,
  saveAsJson,
  persistViewport,
  loadViewport,
} from './persistence.ts';
import {
  screenToWorld,
  zoomAtPoint,
  zoomAtCenter as zoomAtCenterFn,
  ZOOM_STEP,
  type ViewportState,
} from './viewport.ts';
import {
  createWallWindow,
  createWallDoor,
  createWallOpening,
  hitWallObjectInRooms,
  hitWallObjectEdgeInRooms,
  nearestWallSide,
  clampWallObjects,
  computeWallObjectPosition,
  computeWallObjectResize,
  drawOutwardDoorsOverlay,
} from './wall-object.ts';
import {
  createStraightStairs,
  createFoldingStairs,
  createMarker,
  hitInteriorObjectInRooms,
  hitInteriorObjectHandleInRooms,
  computeInteriorObjectMove,
  computeInteriorObjectResize,
  clampAllInteriorObjects,
} from './interior-object.ts';
import {
  createFreeText,
  drawFreeText,
  drawFreeTextHandles,
  hitFreeText,
  hitFreeTextHandle,
  findFreeTextsInArea,
  computeFreeTextResize,
} from './free-text.ts';
import type { ContextMenuItem } from './context-menu.ts';
import { bringToFront, sendToBack, bringForward, sendBackward } from './z-order.ts';
import {
  expandWithLinked,
  linkRooms,
  unlinkRooms,
  cleanupSingletonGroups,
  hasAdjacentPair,
  hasLinkedRoom,
  allAlreadyLinked,
} from './link.ts';
import {
  syncPairedOpening,
  removePairedOpening,
  syncAllPairedOpenings,
  isAutoGeneratedOpening,
} from './adjacency.ts';

export interface RoomEditData {
  label: string;
  fontSize: number | undefined;
  autoFontSize: number;
}

export interface MarkerEditData {
  label: string;
}

export interface ContextMenuRequest {
  screenX: number;
  screenY: number;
  items: ContextMenuItem[];
}

export interface EditorCallbacks {
  onStatusChange: (text: string) => void;
  onRoomEdit: (data: RoomEditData) => Promise<{ label: string; fontSize?: number } | null>;
  onMarkerEdit: (data: MarkerEditData) => Promise<{ label: string } | null>;
  onFreeTextEdit: (data: FreeTextEditData) => Promise<{ label: string; fontSize: number } | null>;
  onContextMenu: (request: ContextMenuRequest) => void;
}

export interface EditorAPI {
  undo: () => void;
  newProject: () => void;
  loadProject: (data: { rooms: Room[]; freeTexts: FreeText[] }) => void;
  saveProject: () => void;
  exportAsPng: () => void;
  resize: () => void;
  destroy: () => void;
}

export function initEditor(
  canvas: HTMLCanvasElement,
  container: HTMLElement,
  callbacks: EditorCallbacks,
): EditorAPI {
  const ctx = canvas.getContext('2d')!;

  const state: EditorState = {
    rooms: [],
    freeTexts: [],
    selection: new Set(),
    history: [],
    drag: null,
    mouse: { px: 0, py: 0, gx: 0, gy: 0 },
  };

  const viewport: ViewportState = { zoom: 1, panX: 0, panY: 0 };
  let isPanning = false;
  let activeInteriorObjectId: string | undefined;
  let activeFreeTextId: string | undefined;

  /** CJK文字を2カラム換算した表示幅をグリッド単位で返す */
  function labelDisplayWidth(label: string): number {
    const cols = [...label].reduce(
      (n, c) => n + (/[\u3000-\u9fff\uff00-\uffef]/.test(c) ? 2 : 1),
      0,
    );
    return Math.ceil(cols / 2) + 1;
  }

  function mousePos(e: MouseEvent): MouseCoord {
    const rect = canvas.getBoundingClientRect();
    const sx = e.clientX - rect.left;
    const sy = e.clientY - rect.top;
    const { px, py } = screenToWorld(sx, sy, viewport);
    return { px, py, gx: Math.round(px / GRID), gy: Math.round(py / GRID) };
  }

  function render(): void {
    ctx.setTransform(1, 0, 0, 1, 0, 0);
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.fillStyle = '#fff';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    ctx.setTransform(
      viewport.zoom,
      0,
      0,
      viewport.zoom,
      -viewport.panX * viewport.zoom,
      -viewport.panY * viewport.zoom,
    );

    const viewMinX = viewport.panX;
    const viewMinY = viewport.panY;
    const viewMaxX = viewport.panX + canvas.width / viewport.zoom;
    const viewMaxY = viewport.panY + canvas.height / viewport.zoom;
    drawGrid(ctx, viewMinX, viewMinY, viewMaxX, viewMaxY);

    function drawFreeTextLayer(layer: 'front' | 'back'): void {
      for (const ft of state.freeTexts) {
        if (ft.zLayer !== layer) continue;
        drawFreeText(
          ctx,
          ft,
          state.selection.has(ft.id),
          ft.id === activeFreeTextId,
          viewport.zoom,
        );
      }
    }

    drawFreeTextLayer('back');

    const activeWallObjectId =
      state.drag?.type === 'moveWallObject' || state.drag?.type === 'resizeWallObject'
        ? state.drag.objectId
        : undefined;
    const activeIntObjId =
      state.drag?.type === 'moveInteriorObject' || state.drag?.type === 'resizeInteriorObject'
        ? state.drag.objectId
        : activeInteriorObjectId;
    for (const r of state.rooms) {
      const isSelected = state.selection.has(r.id);
      drawRoom(
        ctx,
        r,
        isSelected,
        isSelected && state.selection.size === 1,
        viewport.zoom,
        activeWallObjectId,
        activeIntObjId,
      );
    }

    // 2nd pass: redraw outward doors on top of all rooms to prevent occlusion
    for (const r of state.rooms) {
      const isSelected = state.selection.has(r.id);
      drawOutwardDoorsOverlay(ctx, r, isSelected, viewport.zoom, activeWallObjectId);
    }

    drawFreeTextLayer('front');

    // active FreeText handles
    if (activeFreeTextId) {
      const activeFt = state.freeTexts.find((ft) => ft.id === activeFreeTextId);
      if (activeFt) {
        drawFreeTextHandles(ctx, activeFt, viewport.zoom);
      }
    }

    if (state.drag && state.drag.type === 'create') {
      drawCreationPreview(ctx, state.drag.start, state.drag.cur, viewport.zoom);
    }

    if (state.drag && state.drag.type === 'areaSelect') {
      drawAreaSelectPreview(ctx, state.drag.start, state.drag.cur, viewport.zoom, state.rooms);
    }

    ctx.setTransform(1, 0, 0, 1, 0, 0);
    updateStatus();
  }

  /* eslint-disable no-irregular-whitespace */
  function updateStatus(): void {
    const zoomPct = Math.round(viewport.zoom * 100);
    let text = `(${state.mouse.gx}, ${state.mouse.gy})　部屋: ${state.rooms.length}　|　${zoomPct}%`;
    if (state.selection.size === 1) {
      const sel = getSingleSelected(state.rooms, state.selection);
      if (sel) {
        text += `　|　${sel.label || '(名前なし)'}　${sel.w}×${sel.h}`;
      }
    } else if (state.selection.size > 1) {
      text += `　|　${state.selection.size}個選択中`;
    }
    callbacks.onStatusChange(text);
  }
  /* eslint-enable no-irregular-whitespace */

  function commitChange(fn: () => void): void {
    pushUndo(state.history, state.rooms, state.freeTexts);
    fn();
    render();
    persistToStorage(state.rooms, state.freeTexts);
  }

  function undo(): void {
    const restored = popUndo(state.history);
    if (!restored) return;
    state.rooms = restored.rooms;
    state.freeTexts = restored.freeTexts;
    clearSelection(state.selection);
    activeInteriorObjectId = undefined;
    activeFreeTextId = undefined;
    render();
    persistToStorage(state.rooms, state.freeTexts);
  }

  function newProject(): void {
    if (
      (state.rooms.length || state.freeTexts.length) &&
      !confirm('現在の間取り図をクリアしますか？')
    )
      return;
    commitChange(() => {
      state.rooms = [];
      state.freeTexts = [];
      clearSelection(state.selection);
    });
    activeInteriorObjectId = undefined;
    activeFreeTextId = undefined;
  }

  function loadProjectData(data: { rooms: Room[]; freeTexts: FreeText[] }): void {
    commitChange(() => {
      state.rooms = data.rooms;
      state.freeTexts = data.freeTexts;
      clearSelection(state.selection);
      syncAllPairedOpenings(state.rooms);
    });
    activeInteriorObjectId = undefined;
    activeFreeTextId = undefined;
  }

  function saveProject(): void {
    saveAsJson(state.rooms, state.freeTexts);
  }

  function exportAsPng(): void {
    const prevSelection = new Set(state.selection);
    clearSelection(state.selection);
    const savedActiveFreeTextId = activeFreeTextId;
    activeFreeTextId = undefined;

    const savedViewport = { ...viewport };
    const savedW = canvas.width;
    const savedH = canvas.height;

    try {
      // rooms と FreeText の両方を含むバウンディングボックスを計算
      const bbox =
        state.rooms.length > 0
          ? computeRoomsBoundingBox(state.rooms)
          : { x: Infinity, y: Infinity, w: 0, h: 0 };
      let maxX = bbox.x === Infinity ? -Infinity : bbox.x + bbox.w;
      let maxY = bbox.y === Infinity ? -Infinity : bbox.y + bbox.h;
      let minX = bbox.x === Infinity ? Infinity : bbox.x;
      let minY = bbox.y === Infinity ? Infinity : bbox.y;

      for (const ft of state.freeTexts) {
        const ftX = ft.gx * GRID;
        const ftY = ft.gy * GRID;
        const ftR = ftX + ft.w * GRID;
        const ftB = ftY + ft.h * GRID;
        if (ftX < minX) minX = ftX;
        if (ftY < minY) minY = ftY;
        if (ftR > maxX) maxX = ftR;
        if (ftB > maxY) maxY = ftB;
      }

      // rooms も FreeText もない場合のフォールバック
      if (minX === Infinity) {
        minX = 0;
        minY = 0;
        maxX = 40 * GRID;
        maxY = 30 * GRID;
      }

      const exportBbox = { x: minX, y: minY, w: maxX - minX, h: maxY - minY };
      const maxDim = Math.max(exportBbox.w, exportBbox.h);
      const MAX_EXPORT_SIZE = 16384;
      const exportScale = maxDim > MAX_EXPORT_SIZE ? MAX_EXPORT_SIZE / maxDim : 1;
      if (exportScale < 1) {
        console.warn(
          `PNG export: サイズが上限を超えたため縮小されます (${Math.round(maxDim)}px → ${MAX_EXPORT_SIZE}px)`,
        );
      }
      viewport.zoom = exportScale;
      viewport.panX = exportBbox.x;
      viewport.panY = exportBbox.y;
      canvas.width = Math.max(1, Math.round(exportBbox.w * exportScale));
      canvas.height = Math.max(1, Math.round(exportBbox.h * exportScale));

      render();
      exportPng(canvas);
    } finally {
      canvas.width = savedW;
      canvas.height = savedH;
      Object.assign(viewport, savedViewport);
      for (const id of prevSelection) state.selection.add(id);
      activeFreeTextId = savedActiveFreeTextId;
      render();
    }
  }

  function onMouseDown(e: MouseEvent): void {
    if (e.button === 1 || (e.button === 0 && isPanning)) {
      e.preventDefault();
      const rect = canvas.getBoundingClientRect();
      state.drag = {
        type: 'pan',
        startScreenX: e.clientX - rect.left,
        startScreenY: e.clientY - rect.top,
        startPanX: viewport.panX,
        startPanY: viewport.panY,
      };
      canvas.style.cursor = 'grabbing';
      return;
    }

    const m = mousePos(e);
    const shift = e.shiftKey;

    // Check wall object edge hit (resize) FIRST — on narrow walls, room handles overlap
    const selectedRooms = state.rooms.filter((r) => state.selection.has(r.id));
    const edgeHit = hitWallObjectEdgeInRooms(selectedRooms, m.px, m.py, viewport.zoom, true);
    if (edgeHit) {
      pushUndo(state.history, state.rooms, state.freeTexts);
      activeInteriorObjectId = undefined;
      const horiz = edgeHit.obj.side === 'n' || edgeHit.obj.side === 's';
      state.drag = {
        type: 'resizeWallObject',
        roomId: edgeHit.room.id,
        objectId: edgeHit.obj.id,
        edge: edgeHit.edge,
        origOffset: edgeHit.obj.offset,
        origWidth: edgeHit.obj.width,
      };
      canvas.style.cursor = horiz ? 'ew-resize' : 'ns-resize';
      render();
      return;
    }

    // Check FreeText handle hit (resize) — only for active FreeText
    if (activeFreeTextId) {
      const activeFt = state.freeTexts.find((ft) => ft.id === activeFreeTextId);
      if (activeFt) {
        const ftHandleDir = hitFreeTextHandle(activeFt, m.px, m.py, viewport.zoom);
        if (ftHandleDir) {
          pushUndo(state.history, state.rooms, state.freeTexts);
          state.drag = {
            type: 'resizeFreeText',
            freeTextId: activeFt.id,
            dir: ftHandleDir,
            orig: { gx: activeFt.gx, gy: activeFt.gy, w: activeFt.w, h: activeFt.h },
          };
          canvas.style.cursor = ftHandleDir + '-resize';
          render();
          return;
        }
      }
    }

    // Check interior object handle hit (resize)
    const intHandleHit = hitInteriorObjectHandleInRooms(selectedRooms, m.px, m.py, viewport.zoom);
    if (intHandleHit) {
      pushUndo(state.history, state.rooms, state.freeTexts);
      activeInteriorObjectId = intHandleHit.obj.id;
      state.drag = {
        type: 'resizeInteriorObject',
        roomId: intHandleHit.room.id,
        objectId: intHandleHit.obj.id,
        dir: intHandleHit.dir,
        snapToGrid: intHandleHit.obj.type === 'stairs',
        orig: {
          x: intHandleHit.obj.x,
          y: intHandleHit.obj.y,
          w: intHandleHit.obj.w,
          h: intHandleHit.obj.h,
        },
      };
      canvas.style.cursor = intHandleHit.dir + '-resize';
      render();
      return;
    }

    const handleHit = hitHandle(state.rooms, state.selection, m.px, m.py, viewport.zoom);
    if (handleHit) {
      pushUndo(state.history, state.rooms, state.freeTexts);
      const { handle, room } = handleHit;
      state.drag = {
        type: 'resize',
        dir: handle.dir,
        orig: { x: room.x, y: room.y, w: room.w, h: room.h },
        targetId: room.id,
        start: m,
      };
      return;
    }

    // Check wall object hit (window drag) — skip auto-generated openings
    const wallHit = hitWallObjectInRooms(state.rooms, m.px, m.py, viewport.zoom, true);
    if (wallHit) {
      pushUndo(state.history, state.rooms, state.freeTexts);
      activeInteriorObjectId = undefined;
      state.drag = {
        type: 'moveWallObject',
        roomId: wallHit.room.id,
        objectId: wallHit.obj.id,
      };
      canvas.style.cursor = 'grabbing';
      render();
      return;
    }

    // Check interior object hit (move)
    const intHit = hitInteriorObjectInRooms(state.rooms, m.px, m.py);
    if (intHit) {
      pushUndo(state.history, state.rooms, state.freeTexts);
      selectSingle(state.selection, intHit.room.id);
      activeInteriorObjectId = intHit.obj.id;
      const snapToGrid = intHit.obj.type === 'stairs';
      const curGx = snapToGrid ? m.gx : m.px / GRID;
      const curGy = snapToGrid ? m.gy : m.py / GRID;
      const offsetX = curGx - intHit.room.x - intHit.obj.x;
      const offsetY = curGy - intHit.room.y - intHit.obj.y;
      state.drag = {
        type: 'moveInteriorObject',
        roomId: intHit.room.id,
        objectId: intHit.obj.id,
        offsetX,
        offsetY,
        snapToGrid,
      };
      canvas.style.cursor = 'grabbing';
      render();
      return;
    }

    activeInteriorObjectId = undefined;

    function startFreeTextDrag(ft: FreeText): void {
      activeFreeTextId = ft.id;
      if (shift) {
        toggleSelection(state.selection, ft.id);
      } else {
        selectSingle(state.selection, ft.id);
      }
      pushUndo(state.history, state.rooms, state.freeTexts);
      state.drag = {
        type: 'moveFreeText',
        freeTextId: ft.id,
        offsetGx: m.gx - ft.gx,
        offsetGy: m.gy - ft.gy,
      };
      canvas.style.cursor = 'grabbing';
      render();
    }

    // Check front-layer FreeText hit
    const frontFtHit = hitFreeText(state.freeTexts, m.px, m.py, 'front');
    if (frontFtHit) {
      startFreeTextDrag(frontFtHit);
      return;
    }

    activeFreeTextId = undefined;
    const r = hitRoom(state.rooms, m.px, m.py);
    if (r) {
      if (shift) {
        toggleSelection(state.selection, r.id);
      } else {
        if (!state.selection.has(r.id)) {
          selectSingle(state.selection, r.id);
        }
      }
      if (state.selection.size === 0) {
        render();
        return;
      }
      pushUndo(state.history, state.rooms, state.freeTexts);
      const expanded = expandWithLinked(state.rooms, state.selection);
      const originals = new Map<string, { x: number; y: number }>();
      for (const room of state.rooms) {
        if (expanded.has(room.id)) {
          originals.set(room.id, { x: room.x, y: room.y });
        }
      }
      state.drag = { type: 'move', originals, start: m };
      render();
      return;
    }

    // Check back-layer FreeText hit
    const backFtHit = hitFreeText(state.freeTexts, m.px, m.py, 'back');
    if (backFtHit) {
      startFreeTextDrag(backFtHit);
      return;
    }

    if (!shift) clearSelection(state.selection);
    state.drag = { type: 'create', start: m, cur: m };
    render();
  }

  function onMouseMove(e: MouseEvent): void {
    if (state.drag && state.drag.type === 'pan') {
      const rect = canvas.getBoundingClientRect();
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;
      viewport.panX = state.drag.startPanX - (sx - state.drag.startScreenX) / viewport.zoom;
      viewport.panY = state.drag.startPanY - (sy - state.drag.startScreenY) / viewport.zoom;
      state.mouse = mousePos(e);
      render();
      return;
    }

    const m = mousePos(e);
    state.mouse = m;

    if (!state.drag) {
      if (isPanning) {
        canvas.style.cursor = 'grab';
        updateStatus();
        return;
      }
      const selectedRooms = state.rooms.filter((r) => state.selection.has(r.id));
      const edgeHover = hitWallObjectEdgeInRooms(selectedRooms, m.px, m.py, viewport.zoom, true);
      if (edgeHover) {
        const horiz = edgeHover.obj.side === 'n' || edgeHover.obj.side === 's';
        canvas.style.cursor = horiz ? 'ew-resize' : 'ns-resize';
      } else {
        // FreeText handle hover
        if (activeFreeTextId) {
          const activeFt = state.freeTexts.find((ft) => ft.id === activeFreeTextId);
          if (activeFt) {
            const ftDir = hitFreeTextHandle(activeFt, m.px, m.py, viewport.zoom);
            if (ftDir) {
              canvas.style.cursor = ftDir + '-resize';
              updateStatus();
              return;
            }
          }
        }
        const intHandleHover = hitInteriorObjectHandleInRooms(
          selectedRooms,
          m.px,
          m.py,
          viewport.zoom,
        );
        if (intHandleHover) {
          canvas.style.cursor = intHandleHover.dir + '-resize';
        } else {
          const h = hitHandle(state.rooms, state.selection, m.px, m.py, viewport.zoom);
          if (h) {
            canvas.style.cursor = h.handle.dir + '-resize';
          } else if (hitWallObjectInRooms(state.rooms, m.px, m.py, viewport.zoom, true)) {
            canvas.style.cursor = 'grab';
          } else if (hitInteriorObjectInRooms(state.rooms, m.px, m.py)) {
            canvas.style.cursor = 'grab';
          } else if (hitFreeText(state.freeTexts, m.px, m.py)) {
            canvas.style.cursor = 'grab';
          } else if (hitRoom(state.rooms, m.px, m.py)) {
            canvas.style.cursor = 'move';
          } else {
            canvas.style.cursor = 'crosshair';
          }
        }
      }
      updateStatus();
      return;
    }

    if (state.drag.type === 'create' || state.drag.type === 'areaSelect') {
      state.drag.cur = m;
      // ドラッグ矩形が既存の部屋を完全に包含するかチェックしてモード切替
      const area = normalizeArea(state.drag.start, m);
      const contained = findRoomsInArea(state.rooms, area);
      if (contained.length > 0 && state.drag.type === 'create') {
        state.drag = { type: 'areaSelect', start: state.drag.start, cur: m };
      } else if (contained.length === 0 && state.drag.type === 'areaSelect') {
        state.drag = { type: 'create', start: state.drag.start, cur: m };
      }
    } else if (state.drag.type === 'move') {
      const dx = m.gx - state.drag.start.gx;
      const dy = m.gy - state.drag.start.gy;
      for (const [id, orig] of state.drag.originals) {
        const room = state.rooms.find((r) => r.id === id);
        if (room) {
          room.x = orig.x + dx;
          room.y = orig.y + dy;
        }
      }
    } else if (state.drag.type === 'resize') {
      const o = state.drag.orig;
      const d = state.drag.dir;
      const targetId = state.drag.targetId;
      const target = state.rooms.find((r) => r.id === targetId);
      if (target) {
        if (d.includes('w')) {
          target.x = Math.min(m.gx, o.x + o.w - 1);
          target.w = Math.max(1, o.x + o.w - target.x);
        }
        if (d.includes('e')) {
          target.w = Math.max(1, m.gx - o.x);
        }
        if (d.includes('n')) {
          target.y = Math.min(m.gy, o.y + o.h - 1);
          target.h = Math.max(1, o.y + o.h - target.y);
        }
        if (d.includes('s')) {
          target.h = Math.max(1, m.gy - o.y);
        }
        clampWallObjects(target);
        clampAllInteriorObjects(target);
      }
    } else if (state.drag.type === 'moveWallObject') {
      const drag = state.drag;
      const targetRoom = state.rooms.find((r) => r.id === drag.roomId);
      if (targetRoom) {
        const obj = targetRoom.wallObjects?.find((o) => o.id === drag.objectId);
        if (obj) {
          const pos = computeWallObjectPosition(targetRoom, m.px, m.py, obj.width);
          obj.side = pos.side;
          obj.offset = pos.offset;
          // NOTE: 毎mousemoveで呼ぶためパフォーマンスコストがある。
          // 部屋数が非常に多い間取りでは、デバウンスやmouseup時のみの同期を検討。
          syncPairedOpening(state.rooms, targetRoom, obj);
        }
      }
    } else if (state.drag.type === 'resizeWallObject') {
      const drag = state.drag;
      const targetRoom = state.rooms.find((r) => r.id === drag.roomId);
      if (targetRoom) {
        const obj = targetRoom.wallObjects?.find((o) => o.id === drag.objectId);
        if (obj) {
          const result = computeWallObjectResize(
            targetRoom,
            obj,
            drag.edge,
            m.px,
            m.py,
            drag.origOffset,
            drag.origWidth,
          );
          obj.offset = result.offset;
          obj.width = result.width;
          // NOTE: 毎mousemoveで呼ぶためパフォーマンスコストがある。
          // 部屋数が非常に多い間取りでは、デバウンスやmouseup時のみの同期を検討。
          syncPairedOpening(state.rooms, targetRoom, obj);
        }
      }
    } else if (state.drag.type === 'moveInteriorObject') {
      const drag = state.drag;
      const targetRoom = state.rooms.find((r) => r.id === drag.roomId);
      if (targetRoom) {
        const obj = targetRoom.interiorObjects?.find((o) => o.id === drag.objectId);
        if (obj) {
          const gxF = drag.snapToGrid ? m.gx : m.px / GRID;
          const gyF = drag.snapToGrid ? m.gy : m.py / GRID;
          const pos = computeInteriorObjectMove(
            targetRoom,
            obj,
            gxF,
            gyF,
            drag.offsetX,
            drag.offsetY,
          );
          obj.x = pos.x;
          obj.y = pos.y;
        }
      }
    } else if (state.drag.type === 'resizeInteriorObject') {
      const drag = state.drag;
      const targetRoom = state.rooms.find((r) => r.id === drag.roomId);
      if (targetRoom) {
        const obj = targetRoom.interiorObjects?.find((o) => o.id === drag.objectId);
        if (obj) {
          const gxF = drag.snapToGrid ? m.gx : m.px / GRID;
          const gyF = drag.snapToGrid ? m.gy : m.py / GRID;
          const minSize = drag.snapToGrid ? 1 : 0.25;
          const result = computeInteriorObjectResize(
            targetRoom,
            drag.dir,
            drag.orig,
            gxF,
            gyF,
            minSize,
          );
          obj.x = result.x;
          obj.y = result.y;
          obj.w = result.w;
          obj.h = result.h;
        }
      }
    } else if (state.drag.type === 'moveFreeText') {
      const drag = state.drag;
      const ft = state.freeTexts.find((f) => f.id === drag.freeTextId);
      if (ft) {
        ft.gx = m.gx - drag.offsetGx;
        ft.gy = m.gy - drag.offsetGy;
      }
    } else if (state.drag.type === 'resizeFreeText') {
      const drag = state.drag;
      const ft = state.freeTexts.find((f) => f.id === drag.freeTextId);
      if (ft) {
        const result = computeFreeTextResize(drag.dir, drag.orig, m.gx, m.gy);
        ft.gx = result.gx;
        ft.gy = result.gy;
        ft.w = result.w;
        ft.h = result.h;
      }
    }

    render();
  }

  function onMouseUp(e: MouseEvent): void {
    if (!state.drag) return;

    if (state.drag.type === 'pan') {
      state.drag = null;
      canvas.style.cursor = isPanning ? 'grab' : 'crosshair';
      persistViewport(viewport);
      return;
    }

    if (state.drag.type === 'moveWallObject' || state.drag.type === 'resizeWallObject') {
      const dragRoomId = state.drag.roomId;
      const dragObjId = state.drag.objectId;
      selectSingle(state.selection, dragRoomId);
      state.drag = null;
      // 壁オブジェクトの同期
      const dragRoom = state.rooms.find((r) => r.id === dragRoomId);
      const dragObj = dragRoom?.wallObjects?.find((o) => o.id === dragObjId);
      if (dragRoom && dragObj) {
        syncPairedOpening(state.rooms, dragRoom, dragObj);
      }
      // Cursor will be recalculated on next mousemove; set a reasonable default
      const m = mousePos(e);
      const stillOnWallObj = hitWallObjectInRooms(state.rooms, m.px, m.py, viewport.zoom, true);
      canvas.style.cursor = stillOnWallObj ? 'grab' : 'crosshair';
      render();
      persistToStorage(state.rooms, state.freeTexts);
      return;
    }

    if (state.drag.type === 'moveInteriorObject' || state.drag.type === 'resizeInteriorObject') {
      state.drag = null;
      canvas.style.cursor = 'crosshair';
      render();
      persistToStorage(state.rooms, state.freeTexts);
      return;
    }

    if (state.drag.type === 'moveFreeText' || state.drag.type === 'resizeFreeText') {
      state.drag = null;
      canvas.style.cursor = 'crosshair';
      render();
      persistToStorage(state.rooms, state.freeTexts);
      return;
    }

    if (state.drag.type === 'areaSelect' || state.drag.type === 'create') {
      // mouseup 時点の最終座標で判定する。ドラッグ中のプレビューモード（areaSelect/create）
      // と mouseup 時の包含判定が異なる場合があるが、最終座標での判定を優先する。
      const m = mousePos(e);
      const area = normalizeArea(state.drag.start, m);
      const contained = findRoomsInArea(state.rooms, area);
      const containedFt = findFreeTextsInArea(state.freeTexts, area);
      if (contained.length > 0 || containedFt.length > 0) {
        // 範囲選択: 包含された部屋・FreeTextを選択
        activeFreeTextId = undefined;
        activeInteriorObjectId = undefined;
        if (!e.shiftKey) {
          clearSelection(state.selection);
        }
        for (const r of contained) {
          state.selection.add(r.id);
        }
        for (const ft of containedFt) {
          state.selection.add(ft.id);
        }
      } else if (area.w > 0 && area.h > 0) {
        // 部屋作成: 包含する部屋がなければ新規作成にフォールバック
        pushUndo(state.history, state.rooms, state.freeTexts);
        const room = createRoom(area.x, area.y, area.w, area.h);
        state.rooms.push(room);
        clearSelection(state.selection);
        state.selection.add(room.id);
      }
    } else if (state.drag.type === 'move' || state.drag.type === 'resize') {
      // 部屋の移動・リサイズ後にペア開口を再同期
      syncAllPairedOpenings(state.rooms);
    }

    // 共通クリーンアップ: areaSelect / create / move / resize すべてここを通る
    state.drag = null;
    render();
    persistToStorage(state.rooms, state.freeTexts);
  }

  function onContextMenu(e: MouseEvent): void {
    e.preventDefault();
    const m = mousePos(e);
    const items: ContextMenuItem[] = [];

    // Check if right-clicking on a FreeText (front layer first, then back)
    const ftHit =
      hitFreeText(state.freeTexts, m.px, m.py, 'front') ||
      hitFreeText(state.freeTexts, m.px, m.py, 'back');
    if (ftHit) {
      const ftId = ftHit.id;
      activeFreeTextId = ftId;
      selectSingle(state.selection, ftId);

      items.push({
        label: 'テキストを変更',
        action: async () => {
          const ft = state.freeTexts.find((f) => f.id === ftId);
          if (!ft) return;
          const result = await callbacks.onFreeTextEdit({ label: ft.label, fontSize: ft.fontSize });
          if (!result) return;
          commitChange(() => {
            const current = state.freeTexts.find((f) => f.id === ftId);
            if (!current) return;
            current.label = result.label;
            current.fontSize = result.fontSize;
          });
        },
      });
      items.push({ separator: true });
      items.push({
        label: ftHit.zLayer === 'front' ? '最背面へ切替' : '最前面へ切替',
        action: () => {
          const ft = state.freeTexts.find((f) => f.id === ftId);
          if (!ft) return;
          commitChange(() => {
            ft.zLayer = ft.zLayer === 'front' ? 'back' : 'front';
          });
        },
      });
      items.push({ separator: true });
      items.push({
        label: 'テキストを削除',
        action: () => {
          commitChange(() => {
            state.freeTexts = state.freeTexts.filter((f) => f.id !== ftId);
          });
          activeFreeTextId = undefined;
        },
      });

      callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
      render();
      return;
    }

    // Check if right-clicking on an interior object
    const intObjHit = hitInteriorObjectInRooms(state.rooms, m.px, m.py);
    if (intObjHit) {
      const roomId = intObjHit.room.id;
      const objId = intObjHit.obj.id;
      activeInteriorObjectId = objId;

      if (intObjHit.obj.type === 'stairs') {
        const directions: { label: string; dir: 'n' | 'e' | 's' | 'w' }[] = [
          { label: '↑ 上向き', dir: 'n' },
          { label: '→ 右向き', dir: 'e' },
          { label: '↓ 下向き', dir: 's' },
          { label: '← 左向き', dir: 'w' },
        ];
        for (const d of directions) {
          items.push({
            label: d.label,
            disabled: intObjHit.obj.direction === d.dir,
            action: () => {
              const room = state.rooms.find((r) => r.id === roomId);
              if (!room) return;
              const obj = room.interiorObjects?.find((o) => o.id === objId);
              if (!obj || obj.type !== 'stairs') return;
              commitChange(() => {
                obj.direction = d.dir;
              });
            },
          });
        }
        items.push({ separator: true });
        items.push({
          label: '階段を削除',
          action: () => {
            const room = state.rooms.find((r) => r.id === roomId);
            if (!room) return;
            commitChange(() => {
              room.interiorObjects = room.interiorObjects?.filter((o) => o.id !== objId);
              if (room.interiorObjects?.length === 0) room.interiorObjects = undefined;
            });
            activeInteriorObjectId = undefined;
          },
        });
      }

      if (intObjHit.obj.type === 'marker') {
        items.push({
          label: 'ラベルを変更',
          action: async () => {
            const room = state.rooms.find((r) => r.id === roomId);
            if (!room) return;
            const obj = room.interiorObjects?.find((o) => o.id === objId);
            if (!obj || obj.type !== 'marker') return;
            const result = await callbacks.onMarkerEdit({ label: obj.label ?? '' });
            if (!result) return;
            commitChange(() => {
              obj.label = result.label || undefined;
            });
          },
        });

        if (intObjHit.obj.markerKind === 'body') {
          items.push({ separator: true });
          const directions: { label: string; dir: 'n' | 'e' | 's' | 'w' }[] = [
            { label: '↑ 上向き', dir: 'n' },
            { label: '→ 右向き', dir: 'e' },
            { label: '↓ 下向き', dir: 's' },
            { label: '← 左向き', dir: 'w' },
          ];
          for (const d of directions) {
            items.push({
              label: d.label,
              disabled: intObjHit.obj.direction === d.dir,
              action: () => {
                const room = state.rooms.find((r) => r.id === roomId);
                if (!room) return;
                const obj = room.interiorObjects?.find((o) => o.id === objId);
                if (!obj || obj.type !== 'marker') return;
                commitChange(() => {
                  obj.direction = d.dir;
                });
              },
            });
          }
        }

        items.push({ separator: true });
        items.push({
          label: 'マーカーを削除',
          action: () => {
            const room = state.rooms.find((r) => r.id === roomId);
            if (!room) return;
            commitChange(() => {
              room.interiorObjects = room.interiorObjects?.filter((o) => o.id !== objId);
              if (room.interiorObjects?.length === 0) room.interiorObjects = undefined;
            });
            activeInteriorObjectId = undefined;
          },
        });
      }

      callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
      render();
      return;
    }

    // Check if right-clicking on a wall object
    const wallHit = hitWallObjectInRooms(state.rooms, m.px, m.py, viewport.zoom);
    if (wallHit) {
      const roomId = wallHit.room.id;
      const objId = wallHit.obj.id;
      const hitObj = wallHit.obj;

      // 自動生成された開口は操作不可
      if (isAutoGeneratedOpening(hitObj)) {
        items.push({
          label: 'この開口は隣室と連動しています',
          disabled: true,
          action: () => {},
        });
        callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
        return;
      }

      const removeWallObject = () => {
        const room = state.rooms.find((r) => r.id === roomId);
        if (!room) return;
        commitChange(() => {
          const obj = room.wallObjects?.find((o) => o.id === objId);
          if (obj) removePairedOpening(state.rooms, obj);
          room.wallObjects = room.wallObjects?.filter((o) => o.id !== objId);
          if (room.wallObjects?.length === 0) room.wallObjects = undefined;
        });
      };

      if (hitObj.type === 'door') {
        items.push({
          label: '開き方向を切替',
          action: () => {
            const room = state.rooms.find((r) => r.id === roomId);
            if (!room) return;
            const door = room.wallObjects?.find((o) => o.id === objId);
            if (!door || door.type !== 'door') return;
            commitChange(() => {
              door.swing = door.swing === 'inward' ? 'outward' : 'inward';
            });
          },
        });
        items.push({
          label: 'ヒンジ位置を切替',
          action: () => {
            const room = state.rooms.find((r) => r.id === roomId);
            if (!room) return;
            const door = room.wallObjects?.find((o) => o.id === objId);
            if (!door || door.type !== 'door') return;
            commitChange(() => {
              door.hinge = door.hinge === 'start' ? 'end' : 'start';
            });
          },
        });
        items.push({ label: 'ドアを削除', action: removeWallObject });
      } else if (hitObj.type === 'opening') {
        items.push({ label: '開口を削除', action: removeWallObject });
      } else {
        items.push({ label: '窓を削除', action: removeWallObject });
      }

      callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
      return;
    }

    // Check if right-clicking on a room (offer to place window)
    // Prefer the selected room if the click is within it, so that
    // the user can right-click on a room that is behind another one
    // by selecting it first.
    const hitR = hitRoom(state.rooms, m.px, m.py);
    const singleSel = getSingleSelected(state.rooms, state.selection);
    const contextRoom =
      singleSel && hitR && singleSel.id !== hitR.id && isInsideRoom(singleSel, m.px, m.py)
        ? singleSel
        : hitR;
    if (contextRoom) {
      const roomId = contextRoom.id;
      items.push({
        label: '部屋名を変更',
        action: async () => {
          const room = state.rooms.find((r) => r.id === roomId);
          if (!room) return;
          await applyRoomEdit(room);
        },
      });
      items.push({ separator: true });
      const { side, offset } = nearestWallSide(contextRoom, m.px, m.py);
      const hasOverlap = contextRoom.wallObjects?.some(
        (o) => o.side === side && offset < o.offset + o.width && offset + 1 > o.offset,
      );
      const placeWallObject = (factory: () => WallObject) => {
        const room = state.rooms.find((r) => r.id === roomId);
        if (!room) return;
        commitChange(() => {
          if (!room.wallObjects) room.wallObjects = [];
          const obj = factory();
          room.wallObjects.push(obj);
          syncPairedOpening(state.rooms, room, obj);
        });
      };
      items.push({
        label: '窓を配置',
        disabled: hasOverlap ?? false,
        action: () => placeWallObject(() => createWallWindow(side, offset)),
      });
      items.push({
        label: 'ドアを配置',
        disabled: hasOverlap ?? false,
        action: () => placeWallObject(() => createWallDoor(side, offset)),
      });
      items.push({
        label: '開口を配置',
        disabled: hasOverlap ?? false,
        action: () => placeWallObject(() => createWallOpening(side, offset)),
      });

      // Interior object placement
      const canPlaceStraightStairs = contextRoom.w >= 2 && contextRoom.h >= 3;
      const canPlaceFoldingStairs = contextRoom.w >= 4 && contextRoom.h >= 3;
      items.push({ separator: true });
      items.push({
        label: '直線階段を配置',
        disabled: !canPlaceStraightStairs,
        action: () => {
          const room = state.rooms.find((r) => r.id === roomId);
          if (!room) return;
          const sw = 2,
            sh = 3;
          const sx = Math.max(0, Math.min(Math.floor((room.w - sw) / 2), room.w - sw));
          const sy = Math.max(0, Math.min(Math.floor((room.h - sh) / 2), room.h - sh));
          const stairs = createStraightStairs(sx, sy, sw, sh);
          commitChange(() => {
            if (!room.interiorObjects) room.interiorObjects = [];
            room.interiorObjects.push(stairs);
          });
          activeInteriorObjectId = stairs.id;
        },
      });
      items.push({
        label: '折り返し階段を配置',
        disabled: !canPlaceFoldingStairs,
        action: () => {
          const room = state.rooms.find((r) => r.id === roomId);
          if (!room) return;
          const fw = 4,
            fh = 3;
          const fx = Math.max(0, Math.min(Math.floor((room.w - fw) / 2), room.w - fw));
          const fy = Math.max(0, Math.min(Math.floor((room.h - fh) / 2), room.h - fh));
          const stairs = createFoldingStairs(fx, fy, fw, fh);
          commitChange(() => {
            if (!room.interiorObjects) room.interiorObjects = [];
            room.interiorObjects.push(stairs);
          });
          activeInteriorObjectId = stairs.id;
        },
      });

      // マーカー配置: カーソル位置を基準にオブジェクトの左上を決定
      const cursorRelX = m.px / GRID - contextRoom.x;
      const cursorRelY = m.py / GRID - contextRoom.y;

      const canPlaceBodyMarker = contextRoom.w >= 2 && contextRoom.h >= 1;
      items.push({
        label: '死体を配置',
        disabled: !canPlaceBodyMarker,
        action: () => {
          const room = state.rooms.find((r) => r.id === roomId);
          if (!room) return;
          const mw = 2,
            mh = 1;
          const mx = Math.max(0, Math.min(cursorRelX - mw / 2, room.w - mw));
          const my = Math.max(0, Math.min(cursorRelY - mh / 2, room.h - mh));
          const marker = createMarker(mx, my, mw, mh);
          commitChange(() => {
            if (!room.interiorObjects) room.interiorObjects = [];
            room.interiorObjects.push(marker);
          });
          activeInteriorObjectId = marker.id;
        },
      });
      items.push({
        label: 'マーカーを配置',
        action: async () => {
          const room = state.rooms.find((r) => r.id === roomId);
          if (!room) return;
          const result = await callbacks.onMarkerEdit({ label: '' });
          if (!result) return;
          const mw = Math.max(1, Math.min(labelDisplayWidth(result.label), room.w));
          const mh = 1;
          const mx = Math.max(0, Math.min(cursorRelX - mw / 2, room.w - mw));
          const my = Math.max(0, Math.min(cursorRelY - mh / 2, room.h - mh));
          const marker = createMarker(mx, my, mw, mh, 'e', 'pin', result.label || undefined);
          commitChange(() => {
            if (!room.interiorObjects) room.interiorObjects = [];
            room.interiorObjects.push(marker);
          });
          activeInteriorObjectId = marker.id;
        },
      });
      items.push({
        label: 'テキストを配置',
        action: async () => {
          const room = state.rooms.find((r) => r.id === roomId);
          if (!room) return;
          const result = await callbacks.onMarkerEdit({ label: '' });
          if (!result || !result.label) return;
          const mw = Math.max(1, Math.min(labelDisplayWidth(result.label), room.w));
          const mh = 1;
          const mx = Math.max(0, Math.min(cursorRelX - mw / 2, room.w - mw));
          const my = Math.max(0, Math.min(cursorRelY - mh / 2, room.h - mh));
          const marker = createMarker(mx, my, mw, mh, 'e', 'text', result.label);
          commitChange(() => {
            if (!room.interiorObjects) room.interiorObjects = [];
            room.interiorObjects.push(marker);
          });
          activeInteriorObjectId = marker.id;
        },
      });

      // 連結/連結解除メニュー
      if (
        state.selection.size >= 2 &&
        hasAdjacentPair(state.rooms, state.selection) &&
        !allAlreadyLinked(state.rooms, state.selection)
      ) {
        items.push({ separator: true });
        items.push({
          label: '連結',
          action: () => {
            commitChange(() => {
              linkRooms(state.rooms, state.selection);
            });
          },
        });
      }
      if (hasLinkedRoom(state.rooms, state.selection)) {
        if (items.length > 0 && !('separator' in items[items.length - 1])) {
          items.push({ separator: true });
        }
        items.push({
          label: '連結解除',
          action: () => {
            commitChange(() => {
              unlinkRooms(state.rooms, state.selection);
            });
          },
        });
      }

      const roomIdx = state.rooms.findIndex((r) => r.id === roomId);
      const isFirst = roomIdx === 0;
      const isLast = roomIdx === state.rooms.length - 1;
      items.push({ separator: true });
      items.push({
        label: '最前面へ移動',
        disabled: isLast,
        action: () => commitChange(() => bringToFront(state.rooms, roomId)),
      });
      items.push({
        label: '1つ前面へ移動',
        disabled: isLast,
        action: () => commitChange(() => bringForward(state.rooms, roomId)),
      });
      items.push({
        label: '1つ背面へ移動',
        disabled: isFirst,
        action: () => commitChange(() => sendBackward(state.rooms, roomId)),
      });
      items.push({
        label: '最背面へ移動',
        disabled: isFirst,
        action: () => commitChange(() => sendToBack(state.rooms, roomId)),
      });

      callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
      return;
    }

    // 空白エリアの右クリック: テキストを配置
    items.push({
      label: 'テキストを配置',
      action: async () => {
        const result = await callbacks.onFreeTextEdit({ label: '', fontSize: 14 });
        if (!result || !result.label) return;
        const ft = createFreeText(m.gx, m.gy, result.label, result.fontSize);
        commitChange(() => {
          state.freeTexts.push(ft);
        });
        activeFreeTextId = ft.id;
        selectSingle(state.selection, ft.id);
        render();
      },
    });
    callbacks.onContextMenu({ screenX: e.clientX, screenY: e.clientY, items });
  }

  async function applyRoomEdit(room: Room): Promise<void> {
    const result = await callbacks.onRoomEdit({
      label: room.label || '',
      fontSize: room.fontSize,
      autoFontSize: Math.round(calcAutoFontSize(room)),
    });
    if (result) {
      commitChange(() => {
        room.label = result.label;
        room.fontSize = result.fontSize;
      });
    }
  }

  async function onDblClick(e: MouseEvent): Promise<void> {
    const m = mousePos(e);

    // FreeText double-click → edit (front layer first, then back)
    const ftHit =
      hitFreeText(state.freeTexts, m.px, m.py, 'front') ||
      hitFreeText(state.freeTexts, m.px, m.py, 'back');
    if (ftHit) {
      const ftId = ftHit.id;
      const result = await callbacks.onFreeTextEdit({
        label: ftHit.label,
        fontSize: ftHit.fontSize,
      });
      if (!result || !result.label) return;
      commitChange(() => {
        const ft = state.freeTexts.find((f) => f.id === ftId);
        if (!ft) return;
        ft.label = result.label;
        ft.fontSize = result.fontSize;
      });
      return;
    }

    const intHit = hitInteriorObjectInRooms(state.rooms, m.px, m.py);
    if (intHit && intHit.obj.type === 'marker') {
      const roomId = intHit.room.id;
      const objId = intHit.obj.id;
      const result = await callbacks.onMarkerEdit({ label: intHit.obj.label ?? '' });
      if (!result) return;
      const room = state.rooms.find((r) => r.id === roomId);
      if (!room) return;
      const obj = room.interiorObjects?.find((o) => o.id === objId);
      if (!obj || obj.type !== 'marker') return;
      commitChange(() => {
        obj.label = result.label || undefined;
      });
      return;
    }

    const r = hitRoom(state.rooms, m.px, m.py);
    if (r) {
      await applyRoomEdit(r);
    }
  }

  function onKeyDown(e: KeyboardEvent): void {
    if (e.code === 'Space' && !isPanning && document.activeElement === document.body) {
      e.preventDefault();
      isPanning = true;
      canvas.style.cursor = 'grab';
      return;
    }

    if ((e.metaKey || e.ctrlKey) && (e.key === '=' || e.key === '+')) {
      e.preventDefault();
      const newVp = zoomAtCenterFn(viewport, canvas.width, canvas.height, viewport.zoom * 1.25);
      Object.assign(viewport, newVp);
      render();
      persistViewport(viewport);
      return;
    }
    if ((e.metaKey || e.ctrlKey) && e.key === '-') {
      e.preventDefault();
      const newVp = zoomAtCenterFn(viewport, canvas.width, canvas.height, viewport.zoom / 1.25);
      Object.assign(viewport, newVp);
      render();
      persistViewport(viewport);
      return;
    }
    if ((e.metaKey || e.ctrlKey) && e.key === '0') {
      e.preventDefault();
      viewport.zoom = 1;
      viewport.panX = 0;
      viewport.panY = 0;
      render();
      persistViewport(viewport);
      return;
    }

    if (
      (e.metaKey || e.ctrlKey) &&
      (e.key === ']' || e.key === '[') &&
      state.selection.size === 1
    ) {
      e.preventDefault();
      const roomId = [...state.selection][0];
      const forward = e.key === ']';
      const fn = e.shiftKey
        ? forward
          ? bringToFront
          : sendToBack
        : forward
          ? bringForward
          : sendBackward;
      pushUndo(state.history, state.rooms, state.freeTexts);
      const changed = fn(state.rooms, roomId);
      if (changed) {
        render();
        persistToStorage(state.rooms, state.freeTexts);
      } else {
        state.history.pop();
      }
      return;
    }

    if ((e.key === 'Delete' || e.key === 'Backspace') && document.activeElement === document.body) {
      // Delete active FreeText first
      if (activeFreeTextId) {
        e.preventDefault();
        const activeId = activeFreeTextId;
        commitChange(() => {
          state.freeTexts = state.freeTexts.filter((f) => f.id !== activeId);
        });
        activeFreeTextId = undefined;
        return;
      }
      // Delete active interior object
      if (activeInteriorObjectId) {
        e.preventDefault();
        const activeId = activeInteriorObjectId;
        commitChange(() => {
          for (const room of state.rooms) {
            if (room.interiorObjects?.some((o) => o.id === activeId)) {
              room.interiorObjects = room.interiorObjects?.filter((o) => o.id !== activeId);
              if (room.interiorObjects?.length === 0) room.interiorObjects = undefined;
              break;
            }
          }
        });
        activeInteriorObjectId = undefined;
        return;
      }
      if (state.selection.size > 0) {
        e.preventDefault();
        commitChange(() => {
          // 選択中のFreeTextも削除
          state.freeTexts = state.freeTexts.filter((f) => !state.selection.has(f.id));
          state.rooms = state.rooms.filter((r) => !state.selection.has(r.id));
          cleanupSingletonGroups(state.rooms);
          syncAllPairedOpenings(state.rooms);
          clearSelection(state.selection);
        });
      }
    }
    if ((e.metaKey || e.ctrlKey) && e.key === 'z') {
      e.preventDefault();
      undo();
    }
  }

  function onKeyUp(e: KeyboardEvent): void {
    if (e.code === 'Space') {
      isPanning = false;
      if (!state.drag || state.drag.type !== 'pan') {
        canvas.style.cursor = 'crosshair';
      }
    }
  }

  function onWheel(e: WheelEvent): void {
    e.preventDefault();
    if (state.drag && state.drag.type !== 'pan') return;

    if (e.ctrlKey) {
      const rect = canvas.getBoundingClientRect();
      const sx = e.clientX - rect.left;
      const sy = e.clientY - rect.top;

      const factor = e.deltaY < 0 ? ZOOM_STEP : 1 / ZOOM_STEP;
      const newVp = zoomAtPoint(viewport, sx, sy, viewport.zoom * factor);

      if (newVp.zoom === viewport.zoom) return;

      Object.assign(viewport, newVp);
    } else {
      viewport.panX += e.deltaX / viewport.zoom;
      viewport.panY += e.deltaY / viewport.zoom;
    }

    render();
    persistViewport(viewport);
  }

  function resizeCanvas(): void {
    canvas.width = container.clientWidth;
    canvas.height = container.clientHeight;
    render();
  }

  // Initialize
  resizeCanvas();
  const loaded = loadFromStorage();
  state.rooms = loaded.rooms;
  state.freeTexts = loaded.freeTexts;
  if (loaded.warning) {
    // setTimeout で描画初期化完了後に表示（alert はレンダリングをブロックするため）
    setTimeout(() => alert(loaded.warning), 0);
  }
  // 旧データにautoGeneratedフラグがない可能性があるため、ロード時にペア開口を再構築
  syncAllPairedOpenings(state.rooms);

  const saved = loadViewport();
  if (saved) {
    viewport.zoom = saved.zoom;
    viewport.panX = saved.panX;
    viewport.panY = saved.panY;
  }

  canvas.addEventListener('mousedown', onMouseDown);
  canvas.addEventListener('mousemove', onMouseMove);
  document.addEventListener('mouseup', onMouseUp);
  canvas.addEventListener('dblclick', onDblClick);
  canvas.addEventListener('contextmenu', onContextMenu);
  document.addEventListener('keydown', onKeyDown);
  document.addEventListener('keyup', onKeyUp);
  canvas.addEventListener('wheel', onWheel, { passive: false });

  render();

  return {
    undo,
    newProject,
    loadProject: loadProjectData,
    saveProject,
    exportAsPng,
    resize: resizeCanvas,
    destroy() {
      canvas.removeEventListener('mousedown', onMouseDown);
      canvas.removeEventListener('mousemove', onMouseMove);
      document.removeEventListener('mouseup', onMouseUp);
      canvas.removeEventListener('dblclick', onDblClick);
      canvas.removeEventListener('contextmenu', onContextMenu);
      document.removeEventListener('keydown', onKeyDown);
      document.removeEventListener('keyup', onKeyUp);
      canvas.removeEventListener('wheel', onWheel);
    },
  };
}
