import type {
  Room,
  FreeText,
  WallObject,
  WallWindow,
  WallDoor,
  WallOpening,
  WallSide,
  RoomInteriorObject,
  StraightStairs,
  FoldingStairs,
  Marker,
  SecurityCamera,
  StairsDirection,
  MarkerKind,
} from './types.ts';
import { CAMERA_COLOR_PRESETS } from './camera.ts';

const VALID_SIDES = new Set(['n', 'e', 's', 'w']);
const VALID_WALL_OBJECT_TYPES = new Set(['window', 'door', 'opening']);
const VALID_DOOR_SWINGS = new Set(['inward', 'outward']);
const VALID_DOOR_HINGES = new Set(['start', 'end']);
const VALID_INTERIOR_OBJECT_TYPES = new Set(['stairs', 'marker', 'camera']);
const VALID_STAIRS_TYPES = new Set(['straight', 'folding']);
const VALID_STAIRS_DIRECTIONS = new Set(['n', 'e', 's', 'w']);
const VALID_MARKER_KINDS = new Set(['body', 'pin', 'text']);
/** プリセットカラー値のホワイトリスト。現時点ではプリセット以外のカスタム色は禁止。
 * 将来カラーピッカー等で任意色を許可する場合は、このバリデーションを緩和すること。 */
const VALID_CAMERA_COLORS = new Set(
  Object.values(CAMERA_COLOR_PRESETS).flatMap((c) => [c.fovColor, c.fovStrokeColor]),
);

function restorePairedWithEntry(value: unknown): { roomId: string; objectId: string } | undefined {
  if (
    value &&
    typeof value === 'object' &&
    typeof (value as Record<string, unknown>).roomId === 'string' &&
    typeof (value as Record<string, unknown>).objectId === 'string'
  ) {
    return {
      roomId: (value as Record<string, unknown>).roomId as string,
      objectId: (value as Record<string, unknown>).objectId as string,
    };
  }
  return undefined;
}

function restorePairedWith(value: unknown): { roomId: string; objectId: string }[] | undefined {
  // 新形式: 配列
  if (Array.isArray(value)) {
    const entries = value
      .map((v) => restorePairedWithEntry(v))
      .filter((v): v is { roomId: string; objectId: string } => v !== undefined);
    return entries.length > 0 ? entries : undefined;
  }
  // 旧形式: 単一オブジェクト → 配列に変換（後方互換）
  const single = restorePairedWithEntry(value);
  return single ? [single] : undefined;
}

/** @internal Exported for testing */
export function ensureWallObjectIds(objects: unknown[]): WallObject[] {
  return objects
    .filter((o) => {
      const obj = o as Record<string, unknown>;
      return (
        typeof obj.offset === 'number' &&
        typeof obj.width === 'number' &&
        VALID_SIDES.has(obj.side as string) &&
        VALID_WALL_OBJECT_TYPES.has(obj.type as string)
      );
    })
    .map((o): WallObject => {
      const obj = o as Record<string, unknown>;
      const id = typeof obj.id === 'string' ? obj.id : crypto.randomUUID();
      const side = obj.side as WallSide;
      const offset = obj.offset as number;
      const width = obj.width as number;

      // pairedWith の復元（全typeで共通）
      const pairedWith = restorePairedWith(obj.pairedWith);

      if (obj.type === 'door') {
        const swing = VALID_DOOR_SWINGS.has(obj.swing as string)
          ? (obj.swing as 'inward' | 'outward')
          : 'inward';
        const hinge = VALID_DOOR_HINGES.has(obj.hinge as string)
          ? (obj.hinge as 'start' | 'end')
          : 'start';
        const result: WallDoor = { id, type: 'door', side, offset, width, swing, hinge };
        if (pairedWith) result.pairedWith = pairedWith;
        return result;
      }
      if (obj.type === 'opening') {
        const result: WallOpening = { id, type: 'opening', side, offset, width };
        if (pairedWith) result.pairedWith = pairedWith;
        if (obj.autoGenerated === true) result.autoGenerated = true;
        return result;
      }
      const result: WallWindow = { id, type: 'window', side, offset, width };
      if (pairedWith) result.pairedWith = pairedWith;
      return result;
    });
}

/** @internal Exported for testing */
export function ensureInteriorObjectIds(objects: unknown[]): RoomInteriorObject[] {
  return objects
    .filter((o) => {
      const obj = o as Record<string, unknown>;
      return (
        typeof obj.x === 'number' &&
        typeof obj.y === 'number' &&
        typeof obj.w === 'number' &&
        typeof obj.h === 'number' &&
        VALID_INTERIOR_OBJECT_TYPES.has(obj.type as string)
      );
    })
    .map((o): RoomInteriorObject => {
      const obj = o as Record<string, unknown>;
      const id = typeof obj.id === 'string' ? obj.id : crypto.randomUUID();
      const x = obj.x as number;
      const y = obj.y as number;
      const w = obj.w as number;
      const h = obj.h as number;

      if (obj.type === 'stairs') {
        const direction = VALID_STAIRS_DIRECTIONS.has(obj.direction as string)
          ? (obj.direction as StairsDirection)
          : 'n';
        const stairsType: 'straight' | 'folding' = VALID_STAIRS_TYPES.has(obj.stairsType as string)
          ? (obj.stairsType as 'straight' | 'folding')
          : 'straight';
        if (stairsType === 'folding') {
          return {
            id,
            type: 'stairs',
            stairsType: 'folding',
            direction,
            x,
            y,
            w,
            h,
          } satisfies FoldingStairs;
        }
        return {
          id,
          type: 'stairs',
          stairsType: 'straight',
          direction,
          x,
          y,
          w,
          h,
        } satisfies StraightStairs;
      }

      if (obj.type === 'marker') {
        const direction = VALID_STAIRS_DIRECTIONS.has(obj.direction as string)
          ? (obj.direction as StairsDirection)
          : 'e';
        const markerKind = VALID_MARKER_KINDS.has(obj.markerKind as string)
          ? (obj.markerKind as MarkerKind)
          : 'body';
        const result: Marker = { id, type: 'marker', markerKind, direction, x, y, w, h };
        if (typeof obj.label === 'string' && obj.label) result.label = obj.label;
        return result;
      }

      if (obj.type === 'camera') {
        const defaults = CAMERA_COLOR_PRESETS.blue;
        const angle =
          typeof obj.angle === 'number' && Number.isFinite(obj.angle) ? obj.angle : 0;
        const fovAngle =
          typeof obj.fovAngle === 'number' && Number.isFinite(obj.fovAngle)
            ? Math.max(Math.PI / 36, Math.min(Math.PI / 2, obj.fovAngle))
            : Math.PI / 6;
        // NaN/Infinity → デフォルト値5にフォールバック、有限の範囲外値 → [1, 20]にクランプ
        const fovRange =
          typeof obj.fovRange === 'number' && Number.isFinite(obj.fovRange)
            ? Math.max(1, Math.min(20, obj.fovRange))
            : 5;
        const fovColor =
          typeof obj.fovColor === 'string' && VALID_CAMERA_COLORS.has(obj.fovColor)
            ? obj.fovColor
            : defaults.fovColor;
        const fovStrokeColor =
          typeof obj.fovStrokeColor === 'string' && VALID_CAMERA_COLORS.has(obj.fovStrokeColor)
            ? obj.fovStrokeColor
            : defaults.fovStrokeColor;
        return {
          id,
          type: 'camera',
          x,
          y,
          w,
          h,
          angle,
          fovAngle,
          fovRange,
          fovColor,
          fovStrokeColor,
        } satisfies SecurityCamera;
      }

      // Fallback (shouldn't reach here due to filter, but TypeScript needs it)
      return { id, type: 'stairs', stairsType: 'straight', direction: 'n', x, y, w, h };
    });
}

const VALID_Z_LAYERS = new Set(['front', 'back']);

/** @internal Exported for testing */
export function ensureFreeTextIds(objects: unknown[]): FreeText[] {
  return objects
    .filter((o) => {
      const obj = o as Record<string, unknown>;
      return (
        typeof obj.gx === 'number' &&
        typeof obj.gy === 'number' &&
        typeof obj.w === 'number' &&
        typeof obj.h === 'number' &&
        typeof obj.label === 'string'
      );
    })
    .map((o): FreeText => {
      const obj = o as Record<string, unknown>;
      return {
        id: typeof obj.id === 'string' ? obj.id : crypto.randomUUID(),
        gx: obj.gx as number,
        gy: obj.gy as number,
        w: obj.w as number,
        h: obj.h as number,
        label: obj.label as string,
        fontSize: typeof obj.fontSize === 'number' ? Math.max(4, Math.min(80, obj.fontSize)) : 14,
        zLayer: VALID_Z_LAYERS.has(obj.zLayer as string)
          ? (obj.zLayer as 'front' | 'back')
          : 'front',
      };
    });
}

function ensureIds(rooms: unknown[]): Room[] {
  return rooms.map((r) => {
    const room = r as Record<string, unknown>;
    const result: Room = {
      ...room,
      id: typeof room.id === 'string' ? room.id : crypto.randomUUID(),
      x: room.x as number,
      y: room.y as number,
      w: room.w as number,
      h: room.h as number,
      label: (room.label as string) ?? '',
    } as Room;
    if (typeof room.linkGroup === 'string') {
      result.linkGroup = room.linkGroup;
    } else {
      delete result.linkGroup;
    }
    if (Array.isArray(room.wallObjects) && room.wallObjects.length > 0) {
      result.wallObjects = ensureWallObjectIds(room.wallObjects);
    }
    if (Array.isArray(room.interiorObjects) && room.interiorObjects.length > 0) {
      result.interiorObjects = ensureInteriorObjectIds(room.interiorObjects);
    }
    return result;
  });
}

export interface StorageData {
  rooms: Room[];
  freeTexts: FreeText[];
  /** データが存在したが解析できなかった場合の警告メッセージ */
  warning?: string;
}

const WARNING_UNRECOGNIZED_FORMAT =
  'データ形式を認識できませんでした。データが破損している可能性があります。';

/** @internal Exported for testing */
export function parseStorageData(parsed: unknown): StorageData {
  // 旧形式: 配列（rooms only）
  if (Array.isArray(parsed)) {
    return { rooms: ensureIds(parsed), freeTexts: [] };
  }
  // 新形式: { rooms, freeTexts }
  if (parsed && typeof parsed === 'object') {
    const obj = parsed as Record<string, unknown>;
    if (!Array.isArray(obj.rooms)) {
      return { rooms: [], freeTexts: [], warning: WARNING_UNRECOGNIZED_FORMAT };
    }
    return {
      rooms: ensureIds(obj.rooms),
      freeTexts: Array.isArray(obj.freeTexts) ? ensureFreeTextIds(obj.freeTexts) : [],
    };
  }
  return { rooms: [], freeTexts: [], warning: WARNING_UNRECOGNIZED_FORMAT };
}

export async function saveAsJson(rooms: Room[], freeTexts: FreeText[] = []): Promise<void> {
  const data = { rooms, freeTexts };
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: 'application/json' });

  if (typeof window.showSaveFilePicker === 'function') {
    try {
      const handle = await window.showSaveFilePicker({
        suggestedName: '間取り図.json',
        types: [
          {
            description: 'JSON ファイル',
            accept: { 'application/json': ['.json'] },
          },
        ],
      });
      const writable = await handle.createWritable();
      try {
        await writable.write(blob);
      } finally {
        await writable.close();
      }
      return;
    } catch (err) {
      if (err instanceof DOMException && err.name === 'AbortError') return;
      console.warn('showSaveFilePicker failed, falling back to download:', err);
    }
  }

  // フォールバック: ファイル名を入力してダウンロード
  const filename = prompt('ファイル名を入力してください', '間取り図.json');
  if (!filename) return;
  triggerDownload(URL.createObjectURL(blob), filename);
}

export function loadFromFile(file: File): Promise<StorageData> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (ev) => {
      try {
        const parsed: unknown = JSON.parse(ev.target!.result as string);
        resolve(parseStorageData(parsed));
      } catch (err) {
        reject(err);
      }
    };
    reader.onerror = () => reject(reader.error);
    reader.readAsText(file);
  });
}

export function exportPng(canvas: HTMLCanvasElement): void {
  triggerDownload(canvas.toDataURL('image/png'), '間取り図.png');
}

function triggerDownload(url: string, filename: string): void {
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
