import type {
  Room,
  WallObject,
  WallWindow,
  WallDoor,
  WallOpening,
  WallSide,
  RoomInteriorObject,
  StraightStairs,
  FoldingStairs,
  Marker,
  StairsDirection,
  MarkerKind,
} from './types.ts';
import type { ViewportState } from './viewport.ts';
import { clampZoom } from './viewport.ts';

const STORAGE_KEY = 'madori_data';
const VIEWPORT_KEY = 'madori_viewport';

const VALID_SIDES = new Set(['n', 'e', 's', 'w']);
const VALID_WALL_OBJECT_TYPES = new Set(['window', 'door', 'opening']);
const VALID_DOOR_SWINGS = new Set(['inward', 'outward']);
const VALID_DOOR_HINGES = new Set(['start', 'end']);
const VALID_INTERIOR_OBJECT_TYPES = new Set(['stairs', 'marker']);
const VALID_STAIRS_TYPES = new Set(['straight', 'folding']);
const VALID_STAIRS_DIRECTIONS = new Set(['n', 'e', 's', 'w']);
const VALID_MARKER_KINDS = new Set(['body', 'pin', 'text']);

function restorePairedWithEntry(
  value: unknown,
): { roomId: string; objectId: string } | undefined {
  if (
    value &&
    typeof value === 'object' &&
    typeof (value as Record<string, unknown>).roomId === 'string' &&
    typeof (value as Record<string, unknown>).objectId === 'string'
  ) {
    return {
      roomId: (value as Record<string, unknown>).roomId as string,
      objectId: (value as Record<string, unknown>).objectId as string,
    };
  }
  return undefined;
}

function restorePairedWith(
  value: unknown,
): { roomId: string; objectId: string }[] | undefined {
  // 新形式: 配列
  if (Array.isArray(value)) {
    const entries = value
      .map((v) => restorePairedWithEntry(v))
      .filter((v): v is { roomId: string; objectId: string } => v !== undefined);
    return entries.length > 0 ? entries : undefined;
  }
  // 旧形式: 単一オブジェクト → 配列に変換（後方互換）
  const single = restorePairedWithEntry(value);
  return single ? [single] : undefined;
}

/** @internal Exported for testing */
export function ensureWallObjectIds(objects: unknown[]): WallObject[] {
  return objects
    .filter((o) => {
      const obj = o as Record<string, unknown>;
      return (
        typeof obj.offset === 'number' &&
        typeof obj.width === 'number' &&
        VALID_SIDES.has(obj.side as string) &&
        VALID_WALL_OBJECT_TYPES.has(obj.type as string)
      );
    })
    .map((o): WallObject => {
      const obj = o as Record<string, unknown>;
      const id = typeof obj.id === 'string' ? obj.id : crypto.randomUUID();
      const side = obj.side as WallSide;
      const offset = obj.offset as number;
      const width = obj.width as number;

      // pairedWith の復元（全typeで共通）
      const pairedWith = restorePairedWith(obj.pairedWith);

      if (obj.type === 'door') {
        const swing = VALID_DOOR_SWINGS.has(obj.swing as string)
          ? (obj.swing as 'inward' | 'outward')
          : 'inward';
        const hinge = VALID_DOOR_HINGES.has(obj.hinge as string)
          ? (obj.hinge as 'start' | 'end')
          : 'start';
        const result: WallDoor = { id, type: 'door', side, offset, width, swing, hinge };
        if (pairedWith) result.pairedWith = pairedWith;
        return result;
      }
      if (obj.type === 'opening') {
        const result: WallOpening = { id, type: 'opening', side, offset, width };
        if (pairedWith) result.pairedWith = pairedWith;
        // autoGeneratedフラグの復元。旧データではpairedWithがあるopeningは
        // 自動生成されたものなので、autoGeneratedフラグを付与してマイグレーション
        if (obj.autoGenerated === true || pairedWith) result.autoGenerated = true;
        return result;
      }
      const result: WallWindow = { id, type: 'window', side, offset, width };
      if (pairedWith) result.pairedWith = pairedWith;
      return result;
    });
}

/** @internal Exported for testing */
export function ensureInteriorObjectIds(objects: unknown[]): RoomInteriorObject[] {
  return objects
    .filter((o) => {
      const obj = o as Record<string, unknown>;
      return (
        typeof obj.x === 'number' &&
        typeof obj.y === 'number' &&
        typeof obj.w === 'number' &&
        typeof obj.h === 'number' &&
        VALID_INTERIOR_OBJECT_TYPES.has(obj.type as string)
      );
    })
    .map((o): RoomInteriorObject => {
      const obj = o as Record<string, unknown>;
      const id = typeof obj.id === 'string' ? obj.id : crypto.randomUUID();
      const x = obj.x as number;
      const y = obj.y as number;
      const w = obj.w as number;
      const h = obj.h as number;

      if (obj.type === 'stairs') {
        const direction = VALID_STAIRS_DIRECTIONS.has(obj.direction as string)
          ? (obj.direction as StairsDirection)
          : 'n';
        const stairsType: 'straight' | 'folding' = VALID_STAIRS_TYPES.has(obj.stairsType as string)
          ? (obj.stairsType as 'straight' | 'folding')
          : 'straight';
        if (stairsType === 'folding') {
          return { id, type: 'stairs', stairsType: 'folding', direction, x, y, w, h } satisfies FoldingStairs;
        }
        return { id, type: 'stairs', stairsType: 'straight', direction, x, y, w, h } satisfies StraightStairs;
      }

      if (obj.type === 'marker') {
        const direction = VALID_STAIRS_DIRECTIONS.has(obj.direction as string)
          ? (obj.direction as StairsDirection)
          : 'e';
        const markerKind = VALID_MARKER_KINDS.has(obj.markerKind as string)
          ? (obj.markerKind as MarkerKind)
          : 'body';
        const result: Marker = { id, type: 'marker', markerKind, direction, x, y, w, h };
        if (typeof obj.label === 'string' && obj.label) result.label = obj.label;
        return result;
      }

      // Fallback (shouldn't reach here due to filter, but TypeScript needs it)
      return { id, type: 'stairs', stairsType: 'straight', direction: 'n', x, y, w, h };
    });
}

function ensureIds(rooms: unknown[]): Room[] {
  return rooms.map((r) => {
    const room = r as Record<string, unknown>;
    const result: Room = {
      ...room,
      id: typeof room.id === 'string' ? room.id : crypto.randomUUID(),
      x: room.x as number,
      y: room.y as number,
      w: room.w as number,
      h: room.h as number,
      label: (room.label as string) ?? '',
    } as Room;
    if (typeof room.linkGroup === 'string') {
      result.linkGroup = room.linkGroup;
    } else {
      delete result.linkGroup;
    }
    if (Array.isArray(room.wallObjects) && room.wallObjects.length > 0) {
      result.wallObjects = ensureWallObjectIds(room.wallObjects);
    }
    if (Array.isArray(room.interiorObjects) && room.interiorObjects.length > 0) {
      result.interiorObjects = ensureInteriorObjectIds(room.interiorObjects);
    }
    return result;
  });
}

export function persistToStorage(rooms: Room[]): void {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(rooms));
  } catch {
    // storage full or unavailable
  }
}

export function loadFromStorage(): Room[] {
  try {
    const data = localStorage.getItem(STORAGE_KEY);
    if (!data) return [];
    const parsed: unknown = JSON.parse(data);
    if (Array.isArray(parsed)) {
      return ensureIds(parsed);
    }
  } catch {
    // corrupt data
  }
  return [];
}

export function saveAsJson(rooms: Room[]): void {
  const blob = new Blob([JSON.stringify(rooms, null, 2)], { type: 'application/json' });
  triggerDownload(URL.createObjectURL(blob), '間取り図.json');
}

export function loadFromFile(file: File): Promise<Room[]> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = (ev) => {
      try {
        const parsed: unknown = JSON.parse(ev.target!.result as string);
        if (Array.isArray(parsed)) {
          resolve(ensureIds(parsed));
        } else {
          reject(new Error('Invalid format'));
        }
      } catch (err) {
        reject(err);
      }
    };
    reader.onerror = () => reject(reader.error);
    reader.readAsText(file);
  });
}

export function persistViewport(vp: ViewportState): void {
  try {
    localStorage.setItem(VIEWPORT_KEY, JSON.stringify(vp));
  } catch {
    // storage full or unavailable
  }
}

export function loadViewport(): ViewportState | null {
  try {
    const data = localStorage.getItem(VIEWPORT_KEY);
    if (!data) return null;
    const parsed = JSON.parse(data) as Record<string, unknown>;
    if (
      typeof parsed.zoom === 'number' &&
      typeof parsed.panX === 'number' &&
      typeof parsed.panY === 'number'
    ) {
      if (!Number.isFinite(parsed.panX) || !Number.isFinite(parsed.panY)) return null;
      return { zoom: clampZoom(parsed.zoom), panX: parsed.panX, panY: parsed.panY };
    }
  } catch {
    // corrupt data
  }
  return null;
}

export function exportPng(canvas: HTMLCanvasElement): void {
  triggerDownload(canvas.toDataURL('image/png'), '間取り図.png');
}

function triggerDownload(url: string, filename: string): void {
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
