export type WallSide = 'n' | 'e' | 's' | 'w';

export interface WallObjectBase {
  id: string;
  side: WallSide;
  offset: number;
  width: number;
  pairedWith?: { roomId: string; objectId: string }[];
}

export interface WallWindow extends WallObjectBase {
  type: 'window';
}

export interface WallDoor extends WallObjectBase {
  type: 'door';
  swing: 'inward' | 'outward';
  hinge: 'start' | 'end';
}

export interface WallOpening extends WallObjectBase {
  type: 'opening';
  /** 隣接壁同期で自動生成された開口かどうか */
  autoGenerated?: boolean;
}

export type WallObject = WallWindow | WallDoor | WallOpening;

export type CardinalDirection = 'n' | 'e' | 's' | 'w';
export type StairsDirection = CardinalDirection;

export interface InteriorObjectBase {
  id: string;
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface StraightStairs extends InteriorObjectBase {
  type: 'stairs';
  stairsType: 'straight';
  direction: StairsDirection;
}

export interface FoldingStairs extends InteriorObjectBase {
  type: 'stairs';
  stairsType: 'folding';
  direction: StairsDirection;
}

export type MarkerKind = 'body' | 'pin' | 'text';

export interface Marker extends InteriorObjectBase {
  type: 'marker';
  markerKind: MarkerKind;
  direction: CardinalDirection;
  label?: string;
  fontSize?: number;
}

export interface SecurityCamera extends InteriorObjectBase {
  type: 'camera';
  /** カメラの向き（ラジアン、0=右/東、PI/2=下/南） */
  angle: number;
  /** 視野の半角（ラジアン）。デフォルト PI/6 (30°、全体で60°) */
  fovAngle: number;
  /** 視野の到達距離（グリッド単位）。デフォルト 5 */
  fovRange: number;
  /** 視野コーンの塗りつぶし色。デフォルト 'rgba(0,150,255,0.15)' */
  fovColor: string;
  /** 視野コーンの枠線色。デフォルト 'rgba(0,150,255,0.4)' */
  fovStrokeColor: string;
}

export type CameraColorPreset = 'blue' | 'red' | 'green' | 'yellow';

export type RoomInteriorObject = StraightStairs | FoldingStairs | Marker | SecurityCamera;

export type GridPoint = { gx: number; gy: number };

export interface Room {
  id: string;
  x: number;
  y: number;
  w: number;
  h: number;
  label: string;
  fontSize?: number;
  floor?: number;
  linkGroup?: string;
  wallObjects?: WallObject[];
  interiorObjects?: RoomInteriorObject[];
  /**
   * 4頂点（初期配置時は時計回り: NW,NE,SE,SW）。未設定時は矩形として扱う。
   * 頂点ドラッグ後はインデックスと方角の対応が崩れるが、辺のインデックス順序
   * （0→1, 1→2, 2→3, 3→0 が n, e, s, w に対応）は維持される。
   * 注意: 自己交差する四角形を作ると pointInQuad やドア描画が未定義動作になる。
   * 自己交差防止ガードは将来課題。
   */
  vertices?: [GridPoint, GridPoint, GridPoint, GridPoint];
}

export interface FreeText {
  id: string;
  gx: number;
  gy: number;
  w: number;
  h: number;
  label: string;
  fontSize: number;
  zLayer: 'front' | 'back';
}

export type StickyNoteColor = 'yellow' | 'pink' | 'green' | 'blue';

export interface StickyNote {
  id: string;
  gx: number;
  gy: number;
  w: number;
  h: number;
  label: string;
  fontSize: number;
  color: StickyNoteColor;
}

export interface FreeStroke {
  id: string;
  /** ピクセル座標の点列（ワールド座標系） */
  points: { px: number; py: number }[];
  color: string;
  lineWidth: number;
  opacity: number;
}

export interface Arrow {
  id: string;
  /** ウェイポイント（グリッド座標、最低2点） */
  points: GridPoint[];
  color: string;
  lineWidth: number;
  label?: string;
  fontSize?: number;
}

export interface EntitySnapshot {
  rooms: Room[];
  freeTexts: FreeText[];
  freeStrokes: FreeStroke[];
  arrows: Arrow[];
  stickyNotes: StickyNote[];
}

export interface FreeTextEditData {
  label: string;
  fontSize: number;
  onFontSizePreview?: (fontSize: number | undefined) => void;
}

export interface Project {
  version: number;
  name: string;
  gridSize: number;
  rooms: Room[];
  freeTexts?: FreeText[];
  freeStrokes?: FreeStroke[];
  arrows?: Arrow[];
  stickyNotes?: StickyNote[];
}

export interface MouseCoord {
  px: number;
  py: number;
  gx: number;
  gy: number;
}

export type ResizeDirection = 'n' | 'ne' | 'e' | 'se' | 's' | 'sw' | 'w' | 'nw';
export type CornerDirection = 'nw' | 'ne' | 'se' | 'sw';

export interface Handle {
  px: number;
  py: number;
  dir: ResizeDirection;
}

export interface GroupHandle {
  px: number;
  py: number;
  dir: CornerDirection;
}

export interface GroupScaleOriginal {
  x: number;
  y: number;
  w: number;
  h: number;
  fontSize?: number;
  vertices?: [GridPoint, GridPoint, GridPoint, GridPoint];
  wallObjects?: Array<{ id: string; offset: number; width: number }>;
  interiorObjects?: Array<{
    id: string;
    x: number;
    y: number;
    w: number;
    h: number;
    fovRange?: number;
  }>;
}

export type DragState =
  | { type: 'create'; start: MouseCoord; cur: MouseCoord }
  | { type: 'areaSelect'; start: MouseCoord; cur: MouseCoord }
  | {
      type: 'move';
      originals: Map<
        string,
        { x: number; y: number; vertices?: [GridPoint, GridPoint, GridPoint, GridPoint] }
      >;
      start: MouseCoord;
    }
  | {
      type: 'resize';
      dir: ResizeDirection;
      orig: { x: number; y: number; w: number; h: number };
      targetId: string;
      start: MouseCoord;
    }
  | {
      type: 'pan';
      startScreenX: number;
      startScreenY: number;
      startPanX: number;
      startPanY: number;
    }
  | {
      type: 'moveWallObject';
      roomId: string;
      objectId: string;
    }
  | {
      type: 'resizeWallObject';
      roomId: string;
      objectId: string;
      edge: 'start' | 'end';
      origOffset: number;
      origWidth: number;
    }
  | {
      type: 'moveInteriorObject';
      roomId: string;
      objectId: string;
      offsetX: number;
      offsetY: number;
      snapToGrid: boolean;
    }
  | {
      type: 'resizeInteriorObject';
      roomId: string;
      objectId: string;
      dir: ResizeDirection;
      snapToGrid: boolean;
      orig: { x: number; y: number; w: number; h: number };
    }
  | {
      type: 'moveFreeText';
      freeTextId: string;
      offsetGx: number;
      offsetGy: number;
    }
  | {
      type: 'resizeFreeText';
      freeTextId: string;
      dir: ResizeDirection;
      orig: { gx: number; gy: number; w: number; h: number; fontSize: number };
    }
  | { type: 'paint'; strokeId: string }
  | { type: 'moveStroke'; id: string; offsetPx: number; offsetPy: number }
  | {
      type: 'rotateCameraAngle';
      roomId: string;
      objectId: string;
    }
  | {
      type: 'adjustCameraFovAngle';
      roomId: string;
      objectId: string;
    }
  | {
      type: 'adjustCameraFovRange';
      roomId: string;
      objectId: string;
    }
  | {
      type: 'groupResize';
      dir: CornerDirection;
      origBB: { x: number; y: number; w: number; h: number };
      anchor: { gx: number; gy: number };
      originals: Map<string, GroupScaleOriginal>;
    }
  | {
      type: 'moveVertex';
      roomId: string;
      vertexIndex: number;
    }
  | {
      type: 'moveArrow';
      arrowId: string;
      startGx: number;
      startGy: number;
      origPoints: GridPoint[];
    }
  | {
      type: 'moveArrowPoint';
      arrowId: string;
      pointIndex: number;
    }
  | {
      type: 'drawArrow';
      startPoint: GridPoint;
    }
  | {
      type: 'moveStickyNote';
      stickyNoteId: string;
      offsetGx: number;
      offsetGy: number;
    }
  | {
      type: 'resizeStickyNote';
      stickyNoteId: string;
      dir: ResizeDirection;
      orig: { gx: number; gy: number; w: number; h: number; fontSize: number };
    }
  | null;

export interface EditorState {
  rooms: Room[];
  freeTexts: FreeText[];
  freeStrokes: FreeStroke[];
  arrows: Arrow[];
  stickyNotes: StickyNote[];
  selection: Set<string>;
  history: string[];
  redoHistory: string[];
  drag: DragState;
  mouse: MouseCoord;
  paintMode: boolean;
  paintColor: string;
  paintLineWidth: number;
  paintOpacity: number;
  arrowMode: boolean;
  arrowColor: string;
  arrowLineWidth: number;
}

export interface ProjectMeta {
  id: string;
  name: string;
  createdAt: number;
  updatedAt: number;
}

export interface ProjectData {
  rooms: Room[];
  freeTexts: FreeText[];
  freeStrokes: FreeStroke[];
  arrows?: Arrow[];
  stickyNotes?: StickyNote[];
  viewport: { zoom: number; panX: number; panY: number };
  history: string[];
  redoHistory?: string[];
}

export interface TabState {
  openTabs: string[];
  activeTabId: string;
}
