export type WallSide = 'n' | 'e' | 's' | 'w';

export interface WallObjectBase {
  id: string;
  side: WallSide;
  offset: number;
  width: number;
  pairedWith?: { roomId: string; objectId: string }[];
}

export interface WallWindow extends WallObjectBase {
  type: 'window';
}

export interface WallDoor extends WallObjectBase {
  type: 'door';
  swing: 'inward' | 'outward';
  hinge: 'start' | 'end';
}

export interface WallOpening extends WallObjectBase {
  type: 'opening';
  /** 隣接壁同期で自動生成された開口かどうか */
  autoGenerated?: boolean;
}

export type WallObject = WallWindow | WallDoor | WallOpening;

export type CardinalDirection = 'n' | 'e' | 's' | 'w';
export type StairsDirection = CardinalDirection;

export interface InteriorObjectBase {
  id: string;
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface StraightStairs extends InteriorObjectBase {
  type: 'stairs';
  stairsType: 'straight';
  direction: StairsDirection;
}

export interface FoldingStairs extends InteriorObjectBase {
  type: 'stairs';
  stairsType: 'folding';
  direction: StairsDirection;
}

export type MarkerKind = 'body' | 'pin' | 'text';

export interface Marker extends InteriorObjectBase {
  type: 'marker';
  markerKind: MarkerKind;
  direction: CardinalDirection;
  label?: string;
}

export interface SecurityCamera extends InteriorObjectBase {
  type: 'camera';
  /** カメラの向き（ラジアン、0=右/東、PI/2=下/南） */
  angle: number;
  /** 視野の半角（ラジアン）。デフォルト PI/6 (30°、全体で60°) */
  fovAngle: number;
  /** 視野の到達距離（グリッド単位）。デフォルト 5 */
  fovRange: number;
  /** 視野コーンの塗りつぶし色。デフォルト 'rgba(0,150,255,0.15)' */
  fovColor: string;
  /** 視野コーンの枠線色。デフォルト 'rgba(0,150,255,0.4)' */
  fovStrokeColor: string;
}

export type CameraColorPreset = 'blue' | 'red' | 'green' | 'yellow';

export type RoomInteriorObject = StraightStairs | FoldingStairs | Marker | SecurityCamera;

export interface Room {
  id: string;
  x: number;
  y: number;
  w: number;
  h: number;
  label: string;
  fontSize?: number;
  floor?: number;
  linkGroup?: string;
  wallObjects?: WallObject[];
  interiorObjects?: RoomInteriorObject[];
}

export interface FreeText {
  id: string;
  gx: number;
  gy: number;
  w: number;
  h: number;
  label: string;
  fontSize: number;
  zLayer: 'front' | 'back';
}

export interface FreeTextEditData {
  label: string;
  fontSize: number;
}

export interface Project {
  version: number;
  name: string;
  gridSize: number;
  rooms: Room[];
  freeTexts?: FreeText[];
}

export interface MouseCoord {
  px: number;
  py: number;
  gx: number;
  gy: number;
}

export type ResizeDirection = 'n' | 'ne' | 'e' | 'se' | 's' | 'sw' | 'w' | 'nw';

export interface Handle {
  px: number;
  py: number;
  dir: ResizeDirection;
}

export type DragState =
  | { type: 'create'; start: MouseCoord; cur: MouseCoord }
  | { type: 'areaSelect'; start: MouseCoord; cur: MouseCoord }
  | { type: 'move'; originals: Map<string, { x: number; y: number }>; start: MouseCoord }
  | {
      type: 'resize';
      dir: ResizeDirection;
      orig: { x: number; y: number; w: number; h: number };
      targetId: string;
      start: MouseCoord;
    }
  | {
      type: 'pan';
      startScreenX: number;
      startScreenY: number;
      startPanX: number;
      startPanY: number;
    }
  | {
      type: 'moveWallObject';
      roomId: string;
      objectId: string;
    }
  | {
      type: 'resizeWallObject';
      roomId: string;
      objectId: string;
      edge: 'start' | 'end';
      origOffset: number;
      origWidth: number;
    }
  | {
      type: 'moveInteriorObject';
      roomId: string;
      objectId: string;
      offsetX: number;
      offsetY: number;
      snapToGrid: boolean;
    }
  | {
      type: 'resizeInteriorObject';
      roomId: string;
      objectId: string;
      dir: ResizeDirection;
      snapToGrid: boolean;
      orig: { x: number; y: number; w: number; h: number };
    }
  | {
      type: 'moveFreeText';
      freeTextId: string;
      offsetGx: number;
      offsetGy: number;
    }
  | {
      type: 'resizeFreeText';
      freeTextId: string;
      dir: ResizeDirection;
      orig: { gx: number; gy: number; w: number; h: number };
    }
  | {
      type: 'rotateCameraAngle';
      roomId: string;
      objectId: string;
    }
  | {
      type: 'adjustCameraFovAngle';
      roomId: string;
      objectId: string;
    }
  | {
      type: 'adjustCameraFovRange';
      roomId: string;
      objectId: string;
    }
  | null;

export interface EditorState {
  rooms: Room[];
  freeTexts: FreeText[];
  selection: Set<string>;
  history: string[];
  drag: DragState;
  mouse: MouseCoord;
}
